### ISSUE TITLE
为什么会发送【黄色】弹幕，结果被封了

### ISSUE THREAD

**Issue by Winter-is-comingXK** [lkeme/BiliHelper-personal#100]
。。。。。。。
有人知道这个脚本发送弹幕时的内容从哪来的吗

**Comment by lkeme** [comment]
推荐直接关闭此功能

**Comment by Winter-is-comingXK** [comment]
[![WVshBd.md.png](https://z3.ax1x.com/2021/07/14/WVshBd.md.png)](https://imgtu.com/i/WVshBd)

**Comment by Winter-is-comingXK** [comment]
> 
> 
> 推荐直接关闭此功能

好

**Comment by miku-o** [comment]
![Screenshot_20210714120039](https://user-images.githubusercontent.com/50576818/125559849-9c545610-90e5-4c2f-88e4-8547597eb753.png)
