### ISSUE TITLE
windows环境报错

### ISSUE THREAD

**Issue by MrLv0816** [lkeme/BiliHelper-personal#101]
BH.ERROR: (App) => MSG: Return value of BiliHelper\Core\Task::read() must
LE: C:\Users\Administrator\Desktop\bili\src\core\Task.php LINE: 63 [] []
不断重复此报错 版本为php-7.3.4

**Comment by poly000** [comment]
Win10 + ？
可能是权限问题
建议先放在`D:\`运行

**Comment by MrLv0816** [comment]
> 赢 10
> + ？
> ？ # 问题 ， 希望有一点`D:\`

win server2012R2用bat文件管理员运行 没有用

**Comment by poly000** [comment]
win8啊 我试试能不能在我的win10复现

**Comment by poly000** [comment]
> > 赢 10
> > 
> > * ？
> >   ？ # 问题 ， 希望有一点`D:\`
> 
> win server2012R2用bat文件管理员运行 没有用

开一下debug吧
`conf\user.ini`

**Comment by MrLv0816** [comment]
Active code page: 65001

C:\Users\Administrator\Desktop\bili>CHCP 65001
Active code page: 65001

C:\Users\Administrator\Desktop\bili>C:\phpstudy\xp.cn\soft\php\php7.3.4\php.exe index.php
 [32m[2021-07-14 23:18:47] BH.INFO: (Env) => 欢迎使用 项目: BiliHelper-personal@master 版本: 0.9.7.
10714 [] [] [0m
 [32m[2021-07-14 23:18:47] BH.INFO: (Env) => 使用说明请移步 https://github.com/lkeme/BiliHelper-pe
 查看 [] [] [0m
[0m
 [32m[2021-07-14 23:18:47] BH.INFO: (App) => 执行Loop模式 [] [] [0m
 [] [0m
 [32m[2021-07-14 23:18:47] BH.INFO: (Task) => 任务排程文件存在，继续执行所有任务。 [] [] [0m
�续执行所有任务。 [] [] [0m
��。 [] [] [0m
m
 [31m[2021-07-14 23:18:47] BH.ERROR: (App) => MSG: Return value of BiliHelper\Core\Task::re
y, null returned CODE: 0 FILE: C:\Users\Administrator\Desktop\bili\src\core\Task.php LINE:
 [37m[2021-07-14 23:18:47] BH.DEBUG: REQUEST: http://www.example.com/api.send?text=[ERROR]:
turn+value+of+BiliHelper%5CCore%5CTask%3A%3Aread%28%29+must+be+of+the+type+array%2C+null+re
%5CUsers%5CAdministrator%5CDesktop%5Cbili%5Csrc%5Ccore%5CTask.php+LINE%3A+63 [] [] [0m

**Comment by poly000** [comment]
> Active code page: 65001
> 
> C:\Users\Administrator\Desktop\bili>CHCP 65001
> Active code page: 65001
> 
> C:\Users\Administrator\Desktop\bili>C:\phpstudy\xp.cn\soft\php\php7.3.4\php.exe index.php
> [32m[2021-07-14 23:18:47] BH.INFO: (Env) => 欢迎使用 项目: BiliHelper-personal@master 版本: 0.9.7.
> 10714 [] [] [0m
> [32m[2021-07-14 23:18:47] BH.INFO: (Env) => 使用说明请移步 https://github.com/lkeme/BiliHelper-pe
> 查看 [] [] [0m
> [0m
> [32m[2021-07-14 23:18:47] BH.INFO: (App) => 执行Loop模式 [] [] [0m
> [] [0m
> [32m[2021-07-14 23:18:47] BH.INFO: (Task) => 任务排程文件存在，继续执行所有任务。 [] [] [0m
> �续执行所有任务。 [] [] [0m
> ��。 [] [] [0m
> m
> [31m[2021-07-14 23:18:47] BH.ERROR: (App) => MSG: Return value of BiliHelper\Core\Task::re
> y, null returned CODE: 0 FILE: C:\Users\Administrator\Desktop\bili\src\core\Task.php LINE:
> [37m[2021-07-14 23:18:47] BH.DEBUG: REQUEST: http://www.example.com/api.send?text=[ERROR]:
> turn+value+of+BiliHelper%5CCore%5CTask%3A%3Aread%28%29+must+be+of+the+type+array%2C+null+re
> %5CUsers%5CAdministrator%5CDesktop%5Cbili%5Csrc%5Ccore%5CTask.php+LINE%3A+63 [] [] [0m

看了一下php源码 可能是空的任务排程文件……
具体要等 lkeme 解释了 （我不会PHP）

**Comment by lkeme** [comment]
1. 重新部署一下，是否能复现。
2. task文件夹里是否有文件。 
3. 把task文件夹里清空后重试一下。
4. 错误最好截图，或复制全一点。

**Comment by MrLv0816** [comment]
> 1. 重新部署一下，是否能复现。
> 2. task文件夹里是否有文件。
> 3. 把task文件夹里清空后重试一下。
> 4. 错误最好截图，或复制全一点。

清空task文件夹文件,成功解决,多谢

**Comment by MrLv0816** [comment]
> 1. 重新部署一下，是否能复现。
> 2. task文件夹里是否有文件。
> 3. 把task文件夹里清空后重试一下。
> 4. 错误最好截图，或复制全一点。

配置文件中我把所有的直播间相关都指向一个直播间,连续观看为啥还会跑别的直播间去 = =

**Comment by lkeme** [comment]
什么叫连续观看

**Comment by MrLv0816** [comment]
![image](https://user-images.githubusercontent.com/46812909/125720054-f56f4457-0e3c-411c-b64e-90ee009cb03d.png)
配置文件中我全部指向了64566这个直播间

**Comment by lkeme** [comment]
配置文件的直播间有注释, 并不是针对所有功能。  

不需要，那把所有抽奖关了就行了。

**Comment by MrLv0816** [comment]
![image](https://user-images.githubusercontent.com/46812909/125720433-c356d6d6-5299-449c-b772-15c0a83ca4f6.png)

emmmmm我指的是这个
