### ISSUE TITLE
间隙性网络异常

### ISSUE THREAD

**Issue by bonnyandsky** [lkeme/BiliHelper-personal#108]
群晖docker.部署的项目，
路由器上挂了梯子，绕过大陆ip模式，并把报错日志里的2个域名都放到了不走代理的域名列表里。
但是时不时的还是会连续报错，导致docker自动关闭。不知是什么原因。24小时内必然会出这个问题。

![IMG_20210805_185446](https://user-images.githubusercontent.com/30990861/128339626-e2208732-ce9e-4942-8650-f23f41e44d9f.jpg)
![IMG_20210805_185527](https://user-images.githubusercontent.com/30990861/128339635-8544df87-8959-4d36-b6f5-729695f0fa9d.jpg)

**Comment by lkeme** [comment]
网络问题
