### ISSUE TITLE
多用户吖

### ISSUE THREAD

**Issue by bilibiliapp** [lkeme/BiliHelper-personal#11]
虽然 php index.php example.conf 可以基础解决问题
但是要是挂服务器里 开多个会对带宽压力很大
希望有一个单命令提示符多账户的
多命令提示符对礼物进行推送对服务器带宽很重。
1Mbps的带宽九个号就能跑满。。

**Comment by lkeme** [comment]
语言限制&环境限制，多用户暂时没考虑。

**Comment by bilibiliapp** [comment]
> 语言限制&环境限制，多用户暂时没考虑。

恩，不过还是谢谢大佬提供这么赞的脚本~~
