### ISSUE TITLE
BUG反馈

### ISSUE THREAD

**Issue by dfmjndm** [lkeme/BiliHelper-personal#117]
部署运行了三天后出现了问题
Segmentation fault
![image](https://user-images.githubusercontent.com/57401901/131320878-79cee475-b575-4582-b2e7-81f5c4f1e385.png)
php版本：8.0

**Comment by lkeme** [comment]
检查php扩展 ，是否开启一些特殊的扩展，已知`opcache、xdebug`等扩展可能会出现。关闭即可

**Comment by dfmjndm** [comment]
> 检查php扩展 ，是否开启一些特殊的扩展，已知`opcache、xdebug`等扩展可能会出现。关闭即可

开了opcache，请问在php<8.0的版本这个问题也会出现吗

**Comment by lkeme** [comment]
已经全面转为>8.0，不再向下兼容，所以<8.0 根本不能运行。
