### ISSUE TITLE
海外手机号无法正确检查格式

### ISSUE THREAD

**Issue by mi-ka-n** [lkeme/BiliHelper-personal#120]
使用美国手机号登录时显示“当前用户名不是有效手机号格式”
复现方法：使用手机号登录模式并输入美国手机号（8xxxxxxxxx）
把这行正则改掉正常登陆

https://github.com/lkeme/BiliHelper-personal/blob/cf9181871816d92d5c17f650ab6bdb1ffb1655d6/src/plugin/Login.php#L452

**Comment by lkeme** [comment]
请看清楚配置文件。
