### ISSUE TITLE
BH.ERROR: (App) => MSG: getUid(): Return value must be of type int, string returned CODE: 0 FILE: /root/BiliHelper-personal/src/core/Helpers.php LINE: 83 [] []

### ISSUE THREAD

**Issue by SekiBetu** [lkeme/BiliHelper-personal#131]
![image](https://user-images.githubusercontent.com/38283893/137870614-43567ec1-a7d5-41b6-a82f-22d4df3c83fc.png)

**Comment by SekiBetu** [comment]
没事了，估计是之前仓库的变动导致拉代码有啥问题，全删了重新clone了代码好了

**Comment by SekiBetu** [comment]
再次出现这情况

**Comment by SekiBetu** [comment]
删干净之后重新clone又好了，我算是整不明白了，太玄学了

**Comment by lkeme** [comment]
出现了跳过某些步骤情况，只需要删除`task/tasks_{username}-.json` 对应账户的任务文件即可。
