### ISSUE TITLE
docker报错

### ISSUE THREAD

**Issue by shangsu** [lkeme/BiliHelper-personal#139]
BH.ERROR: (App) => MSG: getEnable(): Return value must be of type bool, null returned CODE: 0 FILE: /app/src/core/Helpers.php LINE: 47 [] []

**Comment by SekiBetu** [comment]
![image](https://user-images.githubusercontent.com/38283893/141834072-133d7af1-324a-4637-8c75-f36504f3aea5.png)
我就不一样了

**Comment by Yue-xin97** [comment]
我也有类似的
![图片](https://user-images.githubusercontent.com/62045108/142088873-e535dc85-671a-4a7b-9bb6-0ff3249a5254.png)

**Comment by vcheckzen** [comment]
> BH.ERROR: (App) => MSG: getEnable(): Return value must be of type bool, null returned CODE: 0 FILE: /app/src/core/Helpers.php LINE: 47 [] []

同
