### ISSUE TITLE
使用邮箱登陆可能导致无法登陆？

### ISSUE THREAD

**Issue by Elegantwolf** [lkeme/BiliHelper-personal#14]
使用邮箱登陆时，账户密码正确，提示“Bilibili.ERROR: 登录失败 {"msg":"账号或者密码错误"} ”
然而实际上账户密码并没有错误
手机登陆则没有相关问题
谢谢

**Comment by Elegantwolf** [comment]
我使用了上一个版本进行了测试，没有出现相关问题，可能的确是程序出现了bug？谢谢作者。

**Comment by lkeme** [comment]
最新版本测试邮箱登陆正常，请问遇到的问题能否复现？是否有多次测试(多个邮箱账户登陆，更换网络等等)？
