### ISSUE TITLE
运行出错 取用户ID出错

### ISSUE THREAD

**Issue by dihaohappy** [lkeme/BiliHelper-personal#147]
![123123](https://user-images.githubusercontent.com/62019352/144312025-c76ed66c-dfa3-42a7-9f0e-65706525d8dd.png)
第一次可以运行，第二次就不行了。。。。
![123123](https://user-images.githubusercontent.com/62019352/144312025-c76ed66c-dfa3-42a7-9f0e-65706525d8dd.png)

**Comment by lkeme** [comment]
https://github.com/lkeme/BiliHelper-personal/issues/131#issuecomment-977543330
