### ISSUE TITLE
关于登录模式1新账号无法登陆的问题

### ISSUE THREAD

**Issue by cloneGeen** [lkeme/BiliHelper-personal#152]
最近更新时使用新账号一直提示有风险，切换账号也一样，提示使用验证码登陆，能否在下次更新时一并更新一下User-Agent

**Comment by lkeme** [comment]
不是UA的问题，这是机制问题，不同设备不同IP等都会导致，推荐使用模式2。

**Comment by cloneGeen** [comment]
目前账号只能模式1，那我更换为自己的ua是否能解决配置问题



| |
em164051
|
|
***@***.***
|
发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年01月21日 15:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [lkeme/BiliHelper-personal] 关于登录模式1新账号无法登陆的问题 (Issue #152) |

不是UA的问题，这是机制问题，不同设备不同IP等都会导致，推荐使用模式2。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 921j** [comment]
新版本梅林上彻底废了么？
之前还能用，上上个星期手贱升了个级，发现要php8，折腾N久终于能运行了，结果发现提示风险无法登录，怀疑是路由上entware的php8不好用又退回到php7的最后一个版本0.9.9，还是不能登录，又退回0.8.1，也不行了……还是装上0.9.9，等了俩星期依然无法登录，模式2和cookies又不知怎么弄，麻了。
