### ISSUE TITLE
Android 客户端直播心跳 API 与源码不一致

### ISSUE THREAD

**Issue by jshensh** [lkeme/BiliHelper-personal#158]
仅对 https://github.com/lkeme/BiliHelper-personal/blob/master/src/plugin/DoubleHeart.php#L64-L79 提出疑问
![image](https://user-images.githubusercontent.com/11555188/154114398-c562f099-8eb7-45b1-ae74-fcf3d532386a.png)
![image](https://user-images.githubusercontent.com/11555188/154114387-d639acbe-5d9e-4e4c-bf2d-0c5b843d02d5.png)
抓包数据显示目前 heartbeat api 有两个：
```
https://live-trace.bilibili.com/xlive/data-interface/v1/heartbeat/mobileHeartBeat
https://live-trace.bilibili.com/xlive/rdata-interface/v1/heartbeat/mobileHeartBeat
```
两个接口均会返回 `heartbeat_interval` 参数以决定下一次 heartbeat 的时间。
其中 /xlive/data-interface 固定返回 60s，以及不知道什么用处的 `secret_rule` 与 `secret_key`。
而 /xlive/data-interface 返回数据比较无序，目测是 30s 以内的随机数。
如果需要全程抓包数据我可以通过 Telegram 发出。

**Comment by lkeme** [comment]
1. [#L64-L79](https://github.com/lkeme/BiliHelper-personal/blob/master/src/plugin/DoubleHeart.php#L64-L79) 已无用，暂未移除。  
2. data-interface 直播心跳
3. rdata-interface 在线心跳
