### ISSUE TITLE
DOCKER版本启动错误

### ISSUE THREAD

**Issue by q123458384** [lkeme/BiliHelper-personal#179]
应该是8.21作者更新了代码，容器启动后自动拉取（mater分支）最新代码，导致无法启动。
错误提示：`Could not open input file: index.php`

**Comment by lkeme** [comment]
线上docker镜像暂未编译，且2.0版本启动方式不一致

**Comment by q123458384** [comment]
好的谢谢L大，1.x版本不更新了 自己先做个不更新的镜像过渡一下

**Comment by lkeme** [comment]
今日内会更新2.0镜像

**Comment by q123458384** [comment]
哈，顺带做一个1.x的镜像呗 谢谢L大
![39CCFC42](https://user-images.githubusercontent.com/37495419/185875488-12cd3eba-ca2e-497f-b093-9e5a5d08f89a.png)
