### ISSUE TITLE
使用Docker启动项目时无法正常启动。

### ISSUE THREAD

**Issue by liuhuok** [lkeme/BiliHelper-personal#180]
2022年8月22日使用Docker启动项目时报错
![image](https://user-images.githubusercontent.com/59185718/185874125-131430af-f5e7-45dc-9403-fb30a7f69896.png)

**Comment by lkeme** [comment]
线上docker镜像暂未编译，且2.0版本启动方式不一致。今日内会更新2.0镜像。

**Comment by liuhuok** [comment]
> 线上docker镜像暂未编译，且2.0版本启动方式不一致。今日内会更新2.0镜像。

感谢回复，大佬幸苦了。
