### ISSUE TITLE
新版docker镜像报 "MSG: Bhp\Request\Request::_getResponse(): Argument #2 ($url)"

### ISSUE THREAD

**Issue by Silentely** [lkeme/BiliHelper-personal#182]
报 空白的帐号和口令 [] []
已经用新版use.ini 填入帐号密码，似乎还是无法传递

附Log与use.ini 

 <q> 
[信息]  正在使用版本V2方案  
[OK]  正在使用传入的环境变量进行用户配置。
 如果需要配置更多选择项，请通过挂载配置文件来传入。具体参考项目中的README。
 https://github.com/lkeme/BiliHelper-personal.git  

[2022-08-24 09:20:21] BHP.INFO: (Env) => 欢迎使用 项目: BiliHelper-personal@master 版本: 2.0.0.220822 [] []
[2022-08-24 09:20:21] BHP.INFO: (Env) => 使用说明请移步 https://github.com/lkeme/BiliHelper-personal 查看 [] []
[2022-08-24 09:20:21] BHP.INFO: (Schedule) => 任务排程文件不存在，初始化所有任务。 [] []
                                                   预加载插件列表
┌─────────────────┬─────────────────┬─────────┬──────────────────────────┬────────┬──────────┬─────────────┬────────┐
│ hook            │ name            │ version │ desc                     │ author │ priority │ cycle       │ status │
├─────────────────┼─────────────────┼─────────┼──────────────────────────┼────────┼──────────┼─────────────┼────────┤
│ CheckUpdate     │ CheckUpdate     │ 0.0.1   │ 检查版本更新             │ Lkeme  │     1000 │ 24(小时)    │ √      │
│ Login           │ Login           │ 0.0.1   │ 登录                     │ Lkeme  │     1001 │ 2(小时)     │ √      │
│ MainSite        │ MainSite        │ 0.0.1   │ 主站任务(观看|分享|投币) │ Lkeme  │     1100 │ 24(小时)    │ √      │
│ Manga           │ Manga           │ 0.0.1   │ 漫画签到/分享            │ Lkeme  │     1101 │ 24(小时)    │ √      │
│ LoveClub        │ LoveClub        │ 0.0.1   │ 友爱社签到               │ Lkeme  │     1102 │ 24(小时)    │ √      │
│ LiveSignIn      │ LiveSignIn      │ 0.0.1   │ 直播签到                 │ Lkeme  │     1103 │ 24(小时)    │ √      │
│ GameForecast    │ GameForecast    │ 0.0.1   │ 赛事预测(破产机)         │ Lkeme  │     1104 │ 24(小时)    │ √      │
│ Silver2Coin     │ Silver2Coin     │ 0.0.1   │ 银瓜子兑换硬币           │ Lkeme  │     1105 │ 24(小时)    │ √      │
│ Judge           │ Judge           │ 0.0.1   │ 風機委員                 │ Lkeme  │     1106 │ 15-30(分钟) │ √      │
│ VipPrivilege    │ VipPrivilege    │ 0.0.1   │ 领取大会员权益           │ Lkeme  │     1107 │ 24(小时)    │ √      │
│ BpConsumption   │ BpConsumption   │ 0.0.1   │ 大会员B币券消费          │ Lkeme  │     1108 │ 24(小时)    │ √      │
│ LiveReservation │ LiveReservation │ 0.0.1   │ 预约直播有奖             │ Lkeme  │     1109 │ 1-3(小时)   │ √      │
│ LiveGoldBox     │ LiveGoldBox     │ 0.0.1   │ 直播金色宝箱(实物抽奖)   │ Lkeme  │     1110 │ 6-10(分钟)  │ √      │
│ AwardRecords    │ AwardRecords    │ 0.0.1   │ 获奖记录                 │ Lkeme  │     1111 │ 5(分钟)     │ √      │
└─────────────────┴─────────────────┴─────────┴──────────────────────────┴────────┴──────────┴─────────────┴────────┘
[2022-08-24 09:20:21] BHP.INFO: (AppCommand) => 执行 [主要模式] 默认功能 [] []
[2022-08-24 09:20:21] BHP.INFO: (CheckUpdate) => 开始检查项目更新 [] []
[2022-08-24 09:20:21] BHP.INFO: (CheckUpdate) => 拉取线上最新配置 [] []
[2022-08-24 09:20:21] BHP.ERROR: (Task) => MSG: Bhp\Request\Request::_getResponse(): Argument #2 ($url) must be of type string, null given, called in /app/src/Request/Request.php on line 489 CODE: 0 FILE: /app/src/Request/Request.php LINE: 251 [] []
[2022-08-24 09:20:21] BHP.INFO: (Login) => 启动登录程序 [] []
[2022-08-24 09:20:21] BHP.INFO: (Login) => 准备载入登录令牌 [] []
[2022-08-24 09:20:21] BHP.ERROR: (Helpers) => 空白的帐号和口令 [] []
[2022-08-24 09:20:21] BHP.ERROR: (Task) => MSG: str_replace(): Argument #3 ($subject) must be of type array|string, null given CODE: 0 FILE: /app/src/Log/Log.php LINE: 211 [] []
TypeError str_replace(): Argument #3 ($subject) must be of type array|string, null given
(thrown in /app/src/Log/Log.php:211)

use.ini 
#######################
#       程序设置       #
#######################

[app]
name = BiliHelper-personal
env = local
branch = master
version = 0.0.1

#######################
#       账户设置       #
#######################

; 帐号/密码
[login_account]
username = XXXXX@qq.com
password = XXXXXXXXX

; 登录模式/[1.账密模式 2.短信验证码模式 3.扫码模式 4.行为验证码模式(暂未开放)]
[login_mode]
mode = 1

; 国家代码/mode=2触发/例：大陆86 澳大利亚61
[login_country]
code = 86

; 校验/mode=2触发/校验国内手机号/国外手机号关闭校验
[login_check]
phone = true 
</q>

**Comment by Silentely** [comment]
docker-compose方式启动：

version: "3.8"
services:
    bilihelper-personal:
        container_name: bili
        environment:
            - MIRRORS=2
            - VERSION=2
        volumes:
            - /opt/bili/user.ini:/app/conf/user.ini
        restart: always
        image: lkeme/bilihelper-personal

**Comment by lkeme** [comment]
文档可能有点错误，但是VERSION=2 现在是文件夹映射 `-v /path/to/your/confFilePath:/app/profile/user`  
[lkeme/bilihelper-personal](https://github.com/lkeme/BiliHelper-personal/blob/master/docs/DOC.md#docker使用指南)

**Comment by Silentely** [comment]
啊🤔 知道问题了，新版改了路径。抱歉
