### ISSUE TITLE
新版docker镜像账号异常错误

### ISSUE THREAD

**Issue by GOOD-AN** [lkeme/BiliHelper-personal#184]
使用版本V2方案，在每日复位排程文件后，会出现账号异常的报错，重新启动后可正常运行。
![image](https://user-images.githubusercontent.com/53306377/187577904-21d65eb7-3088-4c92-ae48-e994c963bf67.png)
![image](https://user-images.githubusercontent.com/53306377/187577869-f7265dfe-5d95-43fa-abdc-247db16ff022.png)

**Comment by lkeme** [comment]
什么方式登录的，在报错的时间段内，有没有在其他端触发登录过(pc,app等)。

**Comment by GOOD-AN** [comment]
通过手机号登录，每次失败的整体流程如图：
![image](https://user-images.githubusercontent.com/53306377/187597419-507c97ca-af97-4504-a46e-d77903672578.png)
报错时间段内没有触发过其他登录，甚至其他任何操作都没有。

**Comment by lkeme** [comment]
已修复

**Comment by GOOD-AN** [comment]
感谢
