### ISSUE TITLE
视频分享失败

### ISSUE THREAD

**Issue by LordPenguin666** [lkeme/BiliHelper-personal#186]
```
BHP.NOTICE: (MainSite) => 主站任务: XXXX 观看成功 [] []
BHP.WARNING: (MainSite) => 主站任务: XXXX 分享失败 -403 -> 账号异常,操作失败 [] []
```

所有帐号都是分享失败，测试了一下接口，似乎使用aid就会这样，bvid就不会触发风控

**Comment by lkeme** [comment]
这一块不会一直失败，有几率会请求成功，我重新看了一遍API，这块确实是AID参数，应该不是BVID和AID引起的硬性错误，之前稍微研究了一下，猜测是Cookie缺失部分pc的key=>value。
