### ISSUE TITLE
BHP.ERROR

### ISSUE THREAD

**Issue by xchris987** [lkeme/BiliHelper-personal#194]
您好，我是BiliHelper愛用者，近期遇到錯誤提示，已經困擾很久，迫不得已只好來跟您提 issues。
正常執行程序之後一直提示：[2022-11-20 09:30:39] BHP.ERROR: [](Task) => MSG: Control character error, possibly incorrectly encoded CODE: 0 FILE: W:\Backup\BiliHelper-personal\vendor\fire015\flintstone\src\Formatter\JsonFormatter.php LINE: 44 [] []
附上截圖!
![2022-11-20_092835](https://user-images.githubusercontent.com/55051709/202878545-f05a06ef-a87d-4bdc-b050-b70601d98f8f.png)

**Comment by lkeme** [comment]
我这边无法复现，看上去是文件缓存的问题。  
首先备份并删除 `profile/{user}/cache` 目录下的除`cache_Login.dat.gz`和`cache_Request.dat.gz`的其他文件。   
再重新执行一下任务，看看是否报错。  

如果不报错，可以把备份的文件在这里给我。    

如果继续报错，可以把错误再次在这里给我。  

> 只有`Login和Request`里有敏感数据，其他的缓存是无敏的。

**Comment by xchris987** [comment]
谢谢您的回信，按照您的方法删除了cache 下的除了 login 和 request 文件，再重新执行就正常了!
随信附上除了 login 和 request的文件，供您参考，再次感谢帮我解决问题!

lkeme ***@***.***> 於 2022年11月20日 週日 下午4:48寫道：
