### ISSUE TITLE
请教一下视频分享失败。。。

### ISSUE THREAD

**Issue by zhuyaozi** [lkeme/BiliHelper-personal#198]
主站任务: 819691929 分享失败 -403 -> 账号异常,操作失败 [] []
主站任务: 519650903 观看成功 [] [] |
所以的分享全部失败。。。。是风控了吗

**Comment by lkeme** [comment]
不是，不用理会。

**Comment by zhuyaozi** [comment]
额。。不是啊，我试过，可能是真的分享失败，因为等运行结束以后我试过用APP再手动转发，会提示今日首次分享成功+5

**Comment by lkeme** [comment]
不用理会，会自动重试
