### ISSUE TITLE
我有两个问题

### ISSUE THREAD

**Issue by heishanmao** [lkeme/BiliHelper-personal#200]
1，为什么docker run 要加-rm 参数呢？？？这样container 不就没有了嘛？

2。可不可以改变下docker 的思路。。docker 直接封装最新的code，进入docker 就不要再pull git了呀。

谢谢

**Comment by heishanmao** [comment]
![image](https://user-images.githubusercontent.com/16098881/211138869-8eb1a586-6cfb-4687-8dfb-25a1655802fa.png)
并且配置文件已经挂载正确了。还是获取不到登录信息。。我选的短信登陆 不知道是什么原因

**Comment by lkeme** [comment]
首先第一点   `--rm是表示退出容器时会自动删除，并不是你正常运行container就没了`，其次，这是个活动的参数，并不是强制选择，你会你就可以不加。

**Comment by lkeme** [comment]
第二点，我觉得目前的方式是最优解，但是你的思路不同你可以自己改，dockerfile\entrypoint.sh 文件都是在的，需要自定义的可以自定义。

**Comment by lkeme** [comment]
第三个 把配置文件profile/{example} 下的task文件夹删掉

**Comment by heishanmao** [comment]
> 

rm -rf 掉 task 重新启动container 还是获取为空
![image](https://user-images.githubusercontent.com/16098881/211185983-ecd0ded0-4b2a-4e3b-9221-fade515d409d.png)


奇怪的是，task文件下已经有了 用户名.json的文件  user.ini 我只添加了 用户名和密码。然后选择模式1登录 其他什么都没有改，但是container跑不起来

 [信息]  切换源-ghproxy.com  
 ======== 


 ======== 
 [信息]  正使用 git pull 同步项目  
 ======== 

Already up to date.

 ======== 
 [信息]  安装/更新 项目运行依赖  
 ======== 

Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
Nothing to install, update or remove
Generating autoload files
18 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

 
 
 


 ======== 
 [信息]  正在使用版本V2方案  
 ======== 


 ======== 
  正在使用外部配置文件  
 ======== 

[2023-01-08 15:50:06] BHP.INFO: (Env) => 欢迎使用 项目: BiliHelper-personal@master 版本: 2.0.4.221222 [] []
[2023-01-08 15:50:06] BHP.INFO: (Env) => 使用说明请移步 https://github.com/lkeme/BiliHelper-personal 查看 [] []
[2023-01-08 15:50:06] BHP.INFO: (Schedule) => 任务排程文件不存在，初始化所有任务。 [] []
                                                         预加载插件列表
┌─────────────────┬─────────────────┬─────────┬──────────────────────────┬───────────────────┬──────────┬─────────────┬────────┐
│ hook            │ name            │ version │ desc                     │ author            │ priority │ cycle       │ status │
├─────────────────┼─────────────────┼─────────┼──────────────────────────┼───────────────────┼──────────┼─────────────┼────────┤
│ CheckUpdate     │ CheckUpdate     │ 0.0.1   │ 检查版本更新             │ Lkeme             │     1000 │ 24(小时)    │ √      │
│ Login           │ Login           │ 0.0.1   │ 登录                     │ Lkeme             │     1001 │ 2(小时)     │ √      │
│ MainSite        │ MainSite        │ 0.0.1   │ 主站任务(观看|分享|投币) │ Lkeme             │     1100 │ 24(小时)    │ √      │
│ Manga           │ Manga           │ 0.0.1   │ 漫画签到/分享            │ Lkeme             │     1101 │ 24(小时)    │ √      │
│ LoveClub        │ LoveClub        │ 0.0.1   │ 友爱社签到               │ Lkeme             │     1102 │ 24(小时)    │ √      │
│ LiveSignIn      │ LiveSignIn      │ 0.0.1   │ 直播签到                 │ Lkeme             │     1103 │ 24(小时)    │ √      │
│ GameForecast    │ GameForecast    │ 0.0.1   │ 赛事预测(破产机)         │ Lkeme             │     1104 │ 24(小时)    │ √      │
│ Silver2Coin     │ Silver2Coin     │ 0.0.1   │ 银瓜子兑换硬币           │ Lkeme             │     1105 │ 24(小时)    │ √      │
│ Judge           │ Judge           │ 0.0.1   │ 風機委員                 │ Lkeme             │     1106 │ 15-30(分钟) │ √      │
│ VipPrivilege    │ VipPrivilege    │ 0.0.1   │ 领取大会员权益           │ Lkeme             │     1107 │ 24(小时)    │ √      │
│ BpConsumption   │ BpConsumption   │ 0.0.1   │ 大会员B币券消费          │ Lkeme             │     1108 │ 24(小时)    │ √      │
│ LiveReservation │ LiveReservation │ 0.0.1   │ 预约直播有奖             │ Lkeme             │     1109 │ 1-3(小时)   │ √      │
│ LiveGoldBox     │ LiveGoldBox     │ 0.0.1   │ 直播金色宝箱(实物抽奖)   │ Lkeme             │     1110 │ 6-10(分钟)  │ √      │
│ AwardRecords    │ AwardRecords    │ 0.0.1   │ 获奖记录                 │ Lkeme             │     1111 │ 5(分钟)     │ √      │
│ VipPoint        │ VipPoint        │ 0.0.1   │ 大会员积分               │ Lkeme             │     1112 │ 5(分钟)     │ √      │
│ Lottery         │ Lottery         │ 0.0.1   │ 抽奖                     │ MoeHero           │     1113 │ 2-6(小时)   │ √      │
│ DailyGold       │ DailyGold       │ 0.0.1   │ 每日电池(APP)            │ Lkeme             │     1114 │ 24(小时)    │ √      │
│ PolishMedal     │ PolishMedal     │ 0.0.1   │ 点亮徽章                 │ possible318/Lkeme │     1115 │ 1(小时)     │ √      │
└─────────────────┴─────────────────┴─────────┴──────────────────────────┴───────────────────┴──────────┴─────────────┴────────┘
[2023-01-08 15:50:06] BHP.INFO: (AppCommand) => 执行 [主要模式] 默认功能 [] []
[2023-01-08 15:50:06] BHP.INFO: (CheckUpdate) => 开始检查项目更新 [] []
[2023-01-08 15:50:06] BHP.INFO: (CheckUpdate) => 拉取线上最新配置 [] []
[2023-01-08 15:50:08] BHP.INFO: (CheckUpdate) => 程序已是最新版本 [] []
[2023-01-08 15:50:08] BHP.INFO: (Login) => 启动登录程序 [] []
[2023-01-08 15:50:08] BHP.INFO: (Login) => 准备载入登录令牌 [] []
### [2023-01-08 15:50:08] BHP.ERROR: (Helpers) => 空白的帐号和口令 [] []

**Comment by heishanmao** [comment]
我发现 不用配置文件 直接环境变量加”用户名“ ”密码“依然获报错 获取不到。。这个image好奇怪呀

**Comment by lkeme** [comment]
已修复
