### ISSUE TITLE
Lottery.php报错

### ISSUE THREAD

**Issue by junbluedd** [lkeme/BiliHelper-personal#212]
您好，拉取最新项目/换设备/网络/清空配置文件夹均无效，centos7.9  PHP 8.1.13， windows PHP 8.1.19都试过了，问题在上一个版本就有了，貌似删除Lottery文件夹会不报错

日志：

`Warning: Trying to access array offset on value of type null in D:\lingshi1\BiliHelper-personal-master\plugin\Lottery\Lottery.php on line 189
PHP Warning:  Trying to access array offset on value of type null in D:\lingshi1\BiliHelper-personal-master\plugin\Lottery\Lottery.php on line 189

Warning: Trying to access array offset on value of type null in D:\lingshi1\BiliHelper-personal-master\plugin\Lottery\Lottery.php on line 189
PHP Warning:  Trying to access array offset on value of type null in D:\lingshi1\BiliHelper-personal-master\plugin\Lottery\Lottery.php on line 197

Warning: Trying to access array offset on value of type null in D:\lingshi1\BiliHelper-personal-master\plugin\Lottery\Lottery.php on line 197
PHP Warning:  Trying to access array offset on value of type null in D:\lingshi1\BiliHelper-personal-master\plugin\Lottery\Lottery.php on line 199

Warning: Trying to access array offset on value of type null in D:\lingshi1\BiliHelper-personal-master\plugin\Lottery\Lottery.php on line 199
PHP Warning:  Trying to access array offset on value of type null in D:\lingshi1\BiliHelper-personal-master\plugin\Lottery\Lottery.php on line 205

Warning: Trying to access array offset on value of type null in D:\lingshi1\BiliHelper-personal-master\plugin\Lottery\Lottery.php on line 205`

**Comment by lq-259** [comment]
这个是抽奖的 我猜测抽奖坏了 或者账号和ip黑了

**Comment by lkeme** [comment]
是Lottery插件坏了，可以暂时关掉

```
; 动态抽奖&预约直播抽奖
[lottery]
enable = false
; 抽奖模式 0.从最新Id开始抽奖 1.从最新Id的前2400个开始抽奖
lottery_mode = 0
; 直播预约抽奖
live_enable = false
```

**Comment by 17huiwei** [comment]
最新的版本是否已经修复了呢？
