### ISSUE TITLE
关于登录方式的优化

### ISSUE THREAD

**Issue by auqhjjqdo** [lkeme/BiliHelper-personal#213]
现在的3种登录方式，账密和手机验证码方式基本都需要行为验证码，目前需使用临时搭建服务手动验证geetest，从交互逻辑上过于麻烦
使用扫码模式会受制于终端显示，可能出现图片过大或无法显示，建议效仿go-cqhttp在运行目录或user文件夹生成二维码图片方便扫码，或者使用[二维码api访问方式](https://cli.im/api)
同时可以考虑添加cookie或access_key或refresh_token登录方式，直接省去登录步骤

**Comment by lkeme** [comment]
1. 行为验证码现在是最好的处理方式，也不可能公开内置一个自动识别服务
2. 生成二维码图片太不现实，部分用户使用linux和docker方式，看图片并没有那么方便，API方式可以考虑，但从交互方式来说和上述手动验证大差不差了。
3. cookie方式不推荐，内置部分app端api，鉴权或者转换多端过于麻烦，access_key或refresh_token登录方式更不推荐了，并不是所有人都会抓包。

**Comment by auqhjjqdo** [comment]
> * 行为验证码现在是最好的处理方式，也不可能公开内置一个自动识别服务
> * 生成二维码图片太不现实，部分用户使用linux和docker方式，看图片并没有那么方便，API方式可以考虑，但从交互方式来说和上述手动验证大差不差了。
> * cookie方式不推荐，内置部分app端api，鉴权或者转换多端过于麻烦，access_key或refresh_token登录方式更不推荐了，并不是所有人都会抓包。

我现在就是使用的linux的docker环境，如果添加了user目录的映射，看二维码图片也就SFTP打开的事情
api方式只是将二维码内容直接放到参数里然后输出到stdout，用户直接打开链接扫码即可，比起验证码识别方式，docker还要额外设置端口映射，对于使用服务器用户可能还涉及到防火墙，交互方式更加麻烦
另外cookie方式我发现user/cache目录有个cache_Login.dat.gz，里面倒是可以直接修改cookie实现登录，但由于access_key或refresh_token等可能使用不同的appid，在登录时鉴权令牌后需要重新登录，这样又回到了最开始的地方
