### ISSUE TITLE
socket processing is not efficient

### ISSUE THREAD

**Issue by fgggid** [lkeme/BiliHelper-personal#22]
使用 USE_ZONE_SERVER=true 时，但是1秒才处理一轮消息，会导致报文积压，最终socket会超时断连，时不时重连。
另外socket上的read()处理也不是非常好，加上上面的效率提升以后，由于是非阻塞的socket，并不一定一次性就能把length长度的报文收下来，这样就会导致后面的消息处理出现异常。

**Comment by fgggid** [comment]
#23 will fix above issues.

**Comment by lkeme** [comment]
了解，因为USE_ZONE_SERVER目前还是备用状态，没怎么仔细测试性能，没注意到这些，感谢提PR，已合并。

**Comment by fgggid** [comment]
主推送服务器也有类似问题吧？至少1秒一个消息处理看起来似乎是一样的。不过不太清楚它的推送协议，所以就没动。

**Comment by lkeme** [comment]
主备除了连接 、解包，其他处理逻辑基本相同
