### ISSUE TITLE
无法打开验证码页面

### ISSUE THREAD

**Issue by AIEOV** [lkeme/BiliHelper-personal#230]
您好 环境ubuntu22  使用docker或者docker-compose都出现这个问题。旧版本已经全部删除 userini配置修改了新的。
信息中看到app.php是存在的。和#211问题一样。
yml如下

version: '3'
services:
    bhp:
        container_name: bhp
        image: lkeme/bilihelper-personal:latest # my-app: x.x.x
        stdin_open: true # docker run -i 交互模式
        tty: true        # docker run -t 终端模式
        restart: on-failure:5 # 重启策略 / on-failure:5 重启次数5次 / always 一直重启 / unless-stopped 除非停止 / no 从不重启
        volumes:
            - /root/bizhan:/app/profile/user  # /opt/bhp/profile/user替换为自己的路径
        network_mode: bridge # host
        ports:
            - "50001:50001" # 50001替换为自己的端口 user.ini->login_captcha->url
        environment:
            MIRRORS: 0 # 使用github镜像加速 docs/DOC.md#docker使用指南
            CAPTCHA: 1 # docs/CAPTCHA.md

运行后输出

[root@VM-16-16-centos bizhan130]# docker-compose up
[+] Running 1/1
 ✔ Container bhp  Recreated                                                                                                          10.2s 
Attaching to bhp
bhp  | 
bhp  |  ======== 
bhp  |  [信息]  切换源-github.com  
bhp  |  ======== 
bhp  | 
bhp  | 
bhp  |  ======== 
bhp  |  [信息]  正使用 git pull 同步项目  
bhp  |  ======== 
bhp  | 
bhp  | remote: Enumerating objects: 1072, done.
remote: Counting objects: 100% (1072/1072), done.
remote: Compressing objects: 100% (219/219), done.
remote: Total 801 (delta 465), reused 688 (delta 391), pack-reused 0
Receiving objects: 100% (801/801), 112.90 KiB | 628.00 KiB/s, done.
Resolving deltas: 100% (465/465), completed with 145 local objects.
bhp  | From https://github.com/lkeme/BiliHelper-personal
bhp  |    4869d51..5bcc18e  master     -> origin/master
bhp  | Updating 4869d51..5bcc18e
bhp  | Fast-forward
bhp  |  .gitignore                                         |   3 +
bhp  |  LICENSE                                            |   2 +-
bhp  |  README.md                                          |  34 +-
bhp  |  app.php                                            |   2 +-
bhp  |  captcha/index.php                                  |  12 +-
bhp  |  captcha/static/css/style.css                       |   4 +-
bhp  |  captcha/static/index.html                          |  68 +-
bhp  |  captcha/static/js/gt.js                            |   9 +-
bhp  |  captcha/static/js/index.js                         |   5 +-
bhp  |  composer.json                                      | 138 +++--
bhp  |  docker-compose.yml                                 |  18 +
bhp  |  docker/entrypoint.sh                               |  41 +-
bhp  |  docs/CAPTCHA.md                                    |   6 +-
bhp  |  docs/CHANGELOG.md                                  |  85 ++-
bhp  |  docs/DOC.md                                        |  60 +-
bhp  |  plugin/ActivityLottery/ActivityLottery.php         | 332 ++++++++++
bhp  |  plugin/AwardRecords/AwardRecords.php               |   4 +-
bhp  |  plugin/BatchUnfollow/BatchUnfollow.php             | 156 +++++
bhp  |  plugin/BpConsumption/BpConsumption.php             |   4 +-
bhp  |  plugin/CheckUpdate/CheckUpdate.php                 |  16 +-
bhp  |  plugin/DailyGold/DailyGold.php                     |  74 ++-
bhp  |  plugin/GameForecast/GameForecast.php               |   4 +-
bhp  |  plugin/Judge/Judge.php                             |   4 +-
bhp  |  plugin/LiveGoldBox/LiveGoldBox.php                 |   8 +-
bhp  |  plugin/LiveReservation/LiveReservation.php         |   4 +-
bhp  |  plugin/LiveSignIn/LiveSignIn.php                   |   4 +-
bhp  |  plugin/Login/Login.php                             |  93 ++-
bhp  |  plugin/Lottery/Lottery.php                         | 688 ++++++++++++++++-----
bhp  |  plugin/Lottery/LotteryInfo.php                     |   4 +-
bhp  |  plugin/LoveClub/LoveClub.php                       |   4 +-
bhp  |  plugin/MainSite/MainSite.php                       |  17 +-
bhp  |  plugin/Manga/Manga.php                             |   4 +-
bhp  |  plugin/PluginTemplate/PluginTemplate.php           |  18 +-
bhp  |  plugin/PolishMedal/PolishMedal.php                 |  43 +-
bhp  |  plugin/Silver2Coin/Silver2Coin.php                 |   4 +-
bhp  |  plugin/VipPoint/Traits/Bonus.php                   |   5 +-
bhp  |  plugin/VipPoint/Traits/BuyVipMall.php              |   2 +-
bhp  |  plugin/VipPoint/Traits/BuyVipProduct.php           |   2 +-
bhp  |  plugin/VipPoint/Traits/BuyVipVideo.php             |   2 +-
bhp  |  plugin/VipPoint/Traits/CommonTaskInfo.php          |   2 +-
bhp  |  plugin/VipPoint/Traits/DressBuyAmount.php          |  39 ++
bhp  |  plugin/VipPoint/Traits/DressView.php               |  40 ++
bhp  |  plugin/VipPoint/Traits/PointInfo.php               |  15 +-
bhp  |  plugin/VipPoint/Traits/Privilege.php               |   7 +-
bhp  |  plugin/VipPoint/Traits/SignIn.php                  |   2 +-
bhp  |  plugin/VipPoint/Traits/ViewAnimate.php             |   3 +-
bhp  |  plugin/VipPoint/Traits/ViewFilmChannel.php         |   5 +-
bhp  |  plugin/VipPoint/Traits/ViewVideo.php               |   2 +-
bhp  |  plugin/VipPoint/Traits/ViewVipMall.php             |   5 +-
bhp  |  plugin/VipPoint/VipPoint.php                       |  31 +-
bhp  |  plugin/VipPrivilege/VipPrivilege.php               |  51 +-
bhp  |  profile/example/config/user.ini                    |  32 +-
bhp  |  profile/example/device/device.yaml                 |   6 +-
bhp  |  resources/activity_infos.json                      |  54 ++
bhp  |  resources/filter_library.json                      |   4 -
bhp  |  resources/latest_version.json                      |  14 -
bhp  |  resources/version.json                             |  13 +-
bhp  |  src/Api/Api/Pgc/Activity/Deliver/ApiTask.php       |   2 +-
bhp  |  src/Api/Api/Pgc/Activity/Score/ApiTask.php         |   4 +-
bhp  |  src/Api/Api/X/Activity/ApiActivity.php             |  92 +++
bhp  |  src/Api/Api/X/Player/ApiPlayer.php                 |   2 +-
bhp  |  src/Api/Api/X/Relation/ApiRelation.php             | 123 ++++
bhp  |  src/Api/Api/X/VipPoint/ApiTask.php                 |   2 +-
bhp  |  src/Api/Credit/ApiJury.php                         |   2 +-
bhp  |  src/Api/Custom/ApiCalcSign.php                     |   2 +-
bhp  |  src/Api/DynamicSvr/ApiDynamicSvr.php               |   2 +-
bhp  |  src/Api/Esports/ApiGuess.php                       |   2 +-
bhp  |  src/Api/LinkGroup/ApiLoveClub.php                  |   2 +-
bhp  |  src/Api/Lottery/V1/ApiAward.php                    |   2 +-
bhp  |  src/Api/Manga/ApiManga.php                         |   2 +-
bhp  |  src/Api/Msg/ApiMsg.php                             |   2 +-
bhp  |  src/Api/Passport/ApiCaptcha.php                    |   7 +-
bhp  |  src/Api/Passport/ApiLogin.php                      |   2 +-
bhp  |  src/Api/Passport/ApiOauth2.php                     |  12 +-
bhp  |  src/Api/PassportTv/ApiQrcode.php                   |  43 +-
bhp  |  src/Api/Pay/ApiPay.php                             |   2 +-
bhp  |  src/Api/Pay/ApiWallet.php                          |   2 +-
bhp  |  src/Api/Room/V1/ApiArea.php                        |   2 +-
bhp  |  src/Api/Room/V1/ApiDanMu.php                       |   2 +-
bhp  |  src/Api/Room/V1/ApiInfo.php                        |   2 +-
bhp  |  src/Api/Show/Api/Activity/Fire/Common/ApiEvent.php |   2 +-
bhp  |  src/Api/Space/ApiArticle.php                       |  49 ++
bhp  |  src/Api/Space/ApiReservation.php                   |   3 +-
bhp  |  src/Api/Video/ApiCoin.php                          |   2 +-
bhp  |  src/Api/Video/ApiShare.php                         |   2 +-
bhp  |  src/Api/Video/ApiVideo.php                         |   2 +-
bhp  |  src/Api/Video/ApiWatch.php                         |   2 +-
bhp  |  src/Api/Vip/ApiExperience.php                      |  47 ++
bhp  |  src/Api/Vip/ApiPrivilege.php                       |   2 +-
bhp  |  src/Api/Vip/ApiUser.php                            |  55 +-
bhp  |  src/Api/WWW/ApiMain.php                            |   2 +-
bhp  |  src/Api/XLive/ApiRevenueWallet.php                 |   2 +-
bhp  |  src/Api/XLive/ApiXLiveSign.php                     |   2 +-
bhp  |  src/Api/XLive/AppRoom/V1/ApiDM.php                 |   2 +-
bhp  |  src/Api/XLive/AppUcenter/V1/ApiFansMedal.php       |   2 +-
bhp  |  src/Api/XLive/AppUcenter/V1/ApiUserTask.php        |   6 +-
bhp  |  .../DataInterface/V1/HeartBeat/ApiHeartBeat.php    |   2 +-
bhp  |  .../XLive/GeneralInterface/V1/ApiGuardBenefit.php  |   2 +-
bhp  |  src/Api/XLive/LotteryInterface/V1/ApiAnchor.php    |   2 +-
bhp  |  src/Api/XLive/LotteryInterface/V2/ApiBox.php       |   2 +-
bhp  |  src/Api/XLive/Revenue/V1/ApiWallet.php             |   2 +-
bhp  |  src/Api/XLive/WebRoom/V1/Index/ApiIndex.php        |   2 +-
bhp  |  src/Bootstrap/Bootstrap.php                        |   2 +-
bhp  |  src/Cache/Cache.php                                |   2 +-
bhp  |  src/Config/Config.php                              |   2 +-
bhp  |  src/Console/Command/AppCommand.php                 |   2 +-
bhp  |  src/Console/Command/DebugCommand.php               |   2 +-
bhp  |  src/Console/Command/RestoreCommand.php             |   2 +-
bhp  |  src/Console/Command/ScriptCommand.php              |   2 +-
bhp  |  src/Console/Console.php                            |   2 +-
bhp  |  src/Core/Core.php                                  |   2 +-
bhp  |  src/Device/Device.php                              |   2 +-
bhp  |  src/Env/Env.php                                    |   2 +-
bhp  |  src/FilterWords/FilterWords.php                    |   2 +-
bhp  |  src/Helpers.php                                    |   2 +-
bhp  |  src/LiveSign/LiveSign.php                          |  93 +++
bhp  |  src/Log/Log.php                                    |   2 +-
bhp  |  src/Notice/Notice.php                              |  30 +-
bhp  |  src/Plugin/BasePlugin.php                          |   2 +-
bhp  |  src/Plugin/BasePluginInfo.php                      |  28 +-
bhp  |  src/Plugin/BasePluginRW.php                        |   2 +-
bhp  |  src/Plugin/Plugin.php                              |  28 +-
bhp  |  src/Request/MultiRequest.php                       |   6 +-
bhp  |  src/Request/Request.php                            |   4 +-
bhp  |  src/Schedule/Schedule.php                          |   2 +-
bhp  |  src/Sign/Sign.php                                  |   2 +-
bhp  |  src/Task/Task.php                                  |   6 +-
bhp  |  src/TaskQueue/TaskQueue.php                        |   2 +-
bhp  |  src/TimeLock/TimeLock.php                          |  25 +-
bhp  |  src/User/User.php                                  |  21 +-
bhp  |  src/Util/ArrayR/ArrayR.php                         |  12 +-
bhp  |  src/Util/AsciiTable/AsciiTable.php                 |   2 +-
bhp  |  src/Util/Common/Common.php                         |  45 +-
bhp  |  src/Util/DesignPattern/SingleTon.php               |   2 +-
bhp  |  src/Util/Exceptions/GetConfigException.php         |   2 +-
bhp  |  src/Util/Exceptions/HttpClientInitException.php    |   2 +-
bhp  |  src/Util/Exceptions/MethodNotFoundException.php    |   2 +-
bhp  |  src/Util/Exceptions/NoLoginException.php           |   2 +-
bhp  |  src/Util/Exceptions/ResponseEmptyException.php     |   2 +-
bhp  |  src/Util/Exceptions/SingletonException.php         |   2 +-
bhp  |  src/Util/Exceptions/TaskException.php              |   2 +-
bhp  |  src/Util/Fake/Fake.php                             |   4 +-
bhp  |  src/Util/GhProxy/GhProxy.php                       |  35 ++
bhp  |  src/Util/Os/File.php                               |   2 +-
bhp  |  src/Util/Os/Path.php                               |   2 +-
bhp  |  src/Util/Qrcode/Lib/Constants.php                  |   2 +-
bhp  |  src/Util/Qrcode/Lib/FrameFiller.php                |   2 +-
bhp  |  src/Util/Qrcode/Lib/QrBitStream.php                |   2 +-
bhp  |  src/Util/Qrcode/Lib/QrCode.php                     |   2 +-
bhp  |  src/Util/Qrcode/Lib/QrEncode.php                   |   2 +-
bhp  |  src/Util/Qrcode/Lib/QrImage.php                    |   2 +-
bhp  |  src/Util/Qrcode/Lib/QrInput.php                    |   2 +-
bhp  |  src/Util/Qrcode/Lib/QrInputItem.php                |   2 +-
bhp  |  src/Util/Qrcode/Lib/QrMask.php                     |   2 +-
bhp  |  src/Util/Qrcode/Lib/QrRawCode.php                  |   2 +-
bhp  |  src/Util/Qrcode/Lib/QrRs.php                       |   2 +-
bhp  |  src/Util/Qrcode/Lib/QrRsBlock.php                  |   2 +-
bhp  |  src/Util/Qrcode/Lib/QrRsItem.php                   |   2 +-
bhp  |  src/Util/Qrcode/Lib/QrSpec.php                     |   4 +-
bhp  |  src/Util/Qrcode/Lib/QrSplit.php                    |   2 +-
bhp  |  src/Util/Qrcode/Lib/QrStr.php                      |   2 +-
bhp  |  src/Util/Qrcode/Lib/QrTools.php                    |   2 +-
bhp  |  src/Util/Qrcode/Qrcode.php                         |   2 +-
bhp  |  src/Util/Resource/BaseResource.php                 |   2 +-
bhp  |  src/Util/Resource/BaseResourcePoly.php             |   2 +-
bhp  |  src/Util/Resource/Collection.php                   |   2 +-
bhp  |  src/Util/Resource/CollectionInterface.php          |   2 +-
bhp  |  src/Util/Resource/Resource.php                     |   2 +-
bhp  |  src/Util/UUID/UUID.php                             |   2 +-
bhp  |  src/WbiSign/WbiSign.php                            | 106 ++++
bhp  |  src/core/Core.php                                  | 106 ----
bhp  |  tests/AsciiTableTest.php                           |   2 +-
bhp  |  tests/bootstrap.php                                |   2 +-
bhp  |  173 files changed, 2736 insertions(+), 744 deletions(-)
bhp  |  create mode 100644 docker-compose.yml
bhp  |  create mode 100644 plugin/ActivityLottery/ActivityLottery.php
bhp  |  create mode 100644 plugin/BatchUnfollow/BatchUnfollow.php
bhp  |  create mode 100644 plugin/VipPoint/Traits/DressBuyAmount.php
bhp  |  create mode 100644 plugin/VipPoint/Traits/DressView.php
bhp  |  create mode 100644 resources/activity_infos.json
bhp  |  delete mode 100644 resources/latest_version.json
bhp  |  create mode 100644 src/Api/Api/X/Activity/ApiActivity.php
bhp  |  create mode 100644 src/Api/Api/X/Relation/ApiRelation.php
bhp  |  create mode 100644 src/Api/Space/ApiArticle.php
bhp  |  create mode 100644 src/Api/Vip/ApiExperience.php
bhp  |  create mode 100644 src/LiveSign/LiveSign.php
bhp  |  create mode 100644 src/Util/GhProxy/GhProxy.php
bhp  |  create mode 100644 src/WbiSign/WbiSign.php
bhp  |  delete mode 100644 src/core/Core.php
bhp  | 
bhp  |  ======== 
bhp  |  [信息]  安装/更新 项目运行依赖  
bhp  |  ======== 
bhp  | 
bhp  | Installing dependencies from lock file (including require-dev)
bhp  | Verifying lock file contents can be installed on current platform.
bhp  | Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
bhp  | Nothing to install, update or remove
bhp  | Generating autoload files
bhp  | 17 packages you are using are looking for funding.
bhp  | Use the `composer fund` command to find out more!
bhp  | 
bhp  |  
bhp  |  
bhp  |  
bhp  | 
bhp  | 
bhp  |  ======== 
bhp  |  [信息]  正在使用版本V2方案  
bhp  |  ======== 
bhp  | 
bhp  | 
bhp  |  ======== 
bhp  |   正在使用外部配置文件  
bhp  |  ======== 
bhp  | 
bhp  | 
bhp  |  ======== 
bhp  |  [信息]  正在使用验证码服务  
bhp  |  ======== 
bhp  | 
bhp  | 
bhp  |  ======== 
bhp  |  [信息]  验证码服务地址：http://0.0.0.0:50001  
bhp  |  ======== 
bhp  | 
bhp  | Could not open input file: app.php
bhp  | [Sun Mar 10 07:16:45 2024] PHP 8.2.5 Development Server (http://0.0.0.0:50001) started
bhp exited with code 0

**Comment by lkeme** [comment]
docker镜像是最新的吗？是否使用了docker加速镜像？

**Comment by AIEOV** [comment]
docker pull 解决 谢谢
