### ISSUE TITLE
日志报错 ：Error grabbing logs: invalid character '\x00' looking for beginning of value

### ISSUE THREAD

**Issue by declandragon** [lkeme/BiliHelper-personal#231]
# 环境相关
* win10
* Docker Desktop 4.28.0
* 镜像  lkeme/bilihelper-personal:latest  已更新到最新

# 问题描述
之前正常运行了一段时间，突然出现的。

启动的时候就会提示这个，然后就没有日志输出了

# 截图
![image](https://github.com/lkeme/BiliHelper-personal/assets/37643710/9585f762-4467-4a8a-be8a-23f047be1d55)

**Comment by lkeme** [comment]
不是程序问题，是Docker的问题，属于容器日志损坏。  

解决方案：  

1. 找到当前容器的log文件，清空或者删除。
2. 重建容器

**Comment by declandragon** [comment]
> 不是程序问题，是Docker的问题，属于容器日志文件损坏。
> 
> 解决方案：
> 
> 1. 找到当前容器的log文件，清空或者删除。
> 2. 重建容器。



请问是在当前项目里面吗？我看  `profile/user/log` 目录下是空的？

![image](https://github.com/lkeme/BiliHelper-personal/assets/37643710/6ebb0831-0053-4983-8f22-da083f2e8a1e)

**Comment by lkeme** [comment]
跟当前程序日志无关（跟本程序都不想干），是Docker容器的日志坏了。
