### ISSUE TITLE
套接字调用出问题了？

### ISSUE THREAD

**Issue by mentlesoul** [lkeme/BiliHelper-personal#24]
[2020-03-21 21:38:30] Bilibili.ERROR: MSG: Call to undefined function Socket\Raw\socket_create() CODE: 0 FILE: C:\Users\31445\Desktop\BiliHelper-master\BiliHelper-personal-master\vendor\clue\socket-raw\src\Factory.php LINE: 177 [] []

**Comment by lkeme** [comment]
1. 确定是否开启  `extension=php_sockets.dll`
2. 是否执行 `composer install`

**Comment by mentlesoul** [comment]
> 1. 确定是否开启  `extension=php_sockets.dll`
> 2. 是否执行 `composer install`

之前都搞过了，还是这个报错，sockets那个是在php.ini内，composer的那个vender啥的也重新install拉了一遍

**Comment by lkeme** [comment]
不是在不在内，而是看是否启用

**Comment by mentlesoul** [comment]
> 1. 确定是否开启  `extension=php_sockets.dll`
> 2. 是否执行 `composer install`



> 不是在不在内，而是看是否启用

前面;删掉了啊，如果用bilihelper-master就会提示服务繁忙

**Comment by mentlesoul** [comment]
> 不是在不在内，而是看是否启用

前面;删掉了啊，如果用bilihelper-master就会提示服务繁忙

**Comment by lkeme** [comment]
根据给的有限情况，只有这两种可能。

**Comment by mentlesoul** [comment]
> 根据给的有限情况，只有这两种可能。

我php是用微软的web platform installer安装的，但是安装后原本的php.ini内并没有;extension=php_sockets.dll这句

**Comment by lkeme** [comment]
![image](https://user-images.githubusercontent.com/19500576/77228659-c4a27f80-6bc3-11ea-909f-54989af19bfa.png)


刚才我测试把`php_sockets.dll`关闭，复现出来相同的情况，so，你的php配置肯定有问题。

或许是模块本身就不存在，配置加进去也是没用的（猜测）

**Comment by mentlesoul** [comment]
> ![image](https://user-images.githubusercontent.com/19500576/77228659-c4a27f80-6bc3-11ea-909f-54989af19bfa.png)
> 
> 刚才我测试把`php_sockets.dll`关闭，复现出来相同的情况，so，你的php配置肯定有问题。
> 
> 或许是模块本身就不存在，配置加进去也是没用的（猜测）

能找个办法把你php环境发给我么，比如狗度网盘或者qq啥的

**Comment by lkeme** [comment]
抱歉，就是官方原包，可前往 [PHP官网](https://www.php.net/downloads) 直接下载

**Comment by mentlesoul** [comment]
> 抱歉，就是官方原包，可前往 [PHP官网](https://www.php.net/downloads) 直接下载

thread safe还是no thread safe?

**Comment by mentlesoul** [comment]
> 抱歉，就是官方原包，可前往 [PHP官网](https://www.php.net/downloads) 直接下载

尝试了各种办法还是不行。。。求一份php.ini
官方原版7.2-7.4中并没有php.ini只有php.ini-development或者php.ini-product

**Comment by lkeme** [comment]
麻烦请自己先尝试搜索一下？请不要在问这种问题了。

`php.ini-development`和`php.ini-product`都是`php.ini`。

一个生产环境，一个开发环境，名字不一样而已，复制一份重命名就好

**Comment by mentlesoul** [comment]
> 麻烦请自己先尝试搜索一下？请不要在问这种问题了。
> 
> `php.ini-development`和`php.ini-product`都是`php.ini`。
> 
> 一个生产环境，一个开发环境，名字不一样而已，复制一份重命名就好

我搜过了也重命名过了，就是在重命名为php.ini后尝试的包括把ext文件夹路径改为绝对路径，在extension那几行加extension=php_socket.dll啥的都不行

**Comment by 1620827541** [comment]
哦？啥都不行？嗯~~ 负责任告诉你    你电脑坏了  重装系统吧

**Comment by mentlesoul** [comment]
> 哦？啥都不行？嗯~~ 负责任告诉你 你电脑坏了 重装系统吧

俩服务器和自己电脑上试的，服务器装的试官网的，自己电脑是微软web platform installer装的版本都是7.4.x然后都是这个问题困扰了好久了

**Comment by lkeme** [comment]
你不要想着让人手把手教、挤牙膏一样一步骤说一句，都没有那个义务来做。

![image](https://user-images.githubusercontent.com/19500576/77230699-f53ce600-6bd0-11ea-892d-0b9a6acc5c06.png)

这种问题都是能搜出来答案的，且我已经确定百度谷歌上是有答案的。

**Comment by mentlesoul** [comment]
![image](https://user-images.githubusercontent.com/61239889/77241442-116e7080-6c2d-11ea-9920-28a9bb8d913b.png)
![image](https://user-images.githubusercontent.com/61239889/77241458-5b575680-6c2d-11ea-859a-1867daf04388.png)
![image](https://user-images.githubusercontent.com/61239889/77241464-6b6f3600-6c2d-11ea-80c7-d3a9c7516b27.png)
![image](https://user-images.githubusercontent.com/61239889/77241499-c56ffb80-6c2d-11ea-9e1e-2d25cdf01cff.png)

**Comment by mentlesoul** [comment]
![image](https://user-images.githubusercontent.com/61239889/77241821-a0ca5280-6c32-11ea-8155-831f96143f49.png)
![image](https://user-images.githubusercontent.com/61239889/77241832-cbb4a680-6c32-11ea-859a-4cbd2d447097.png)
这两张是配置好的php.ini中extension_dir路径和启用sockets扩展

![image](https://user-images.githubusercontent.com/61239889/77241812-8ee8af80-6c32-11ea-947d-b2c89b3a41e7.png)
![image](https://user-images.githubusercontent.com/61239889/77241817-9740ea80-6c32-11ea-853e-839ac4780202.png)
这个是启用扩展，重启IIS并重新composer install后的错误信息
早上花了三四个小时去google上搜什么“windows下php7开启sockets无效”,“php7怎么开启php_sockets.dll”,“php sockets开启没有效果”啥的找到的都是去掉php_sockets.dll前的;，把extension_dir改为ext文件夹绝对路径什么的。而无论是extension=sockets还是extension=php_sockets.dll都没有用
