### ISSUE TITLE
B站策略更改

### ISSUE THREAD

**Issue by shoucandanghehe** [lkeme/BiliHelper-personal#28]
很多同类型项目的监控都炸了
本项目的也不咋好用了
目前不确定是B站服务器波动还是要改版
先开个issue挂着

**Comment by SenaKawasumi** [comment]
Bilibili改了策略 现在监控服务器全翻车了… 好日子结束了

**Comment by shoucandanghehe** [comment]
屑站

**Comment by LenguesZ** [comment]
你们怎么设的配置？为什么我就开一个小时还是会被封。
你们能正常每日漫画、风纪，直播签到吗？我没设休眠，但过了零点也没有签到。还是说我被封的关系导致的？

**Comment by lkeme** [comment]
监控已修复~

**Comment by shoucandanghehe** [comment]
> 监控已修复~

em
覆盖率大概还能有多少

**Comment by lkeme** [comment]
几乎没影响![image](https://user-images.githubusercontent.com/19500576/79629169-8de76700-8179-11ea-8167-4e353b8cdee6.png)
