### ISSUE TITLE
天选抽奖和银瓜子宝箱与舰长辣条封禁不同步

### ISSUE THREAD

**Issue by LenguesZ** [lkeme/BiliHelper-personal#34]
今天server通知我处于封禁状态，尝试使用本地电脑访问b站。
发现银瓜子宝箱拒绝访问，但可以参与天选抽奖和领取舰长辣条。
请问现在有什么方法让程序单独监视这几项的封禁状态呐？

**Comment by lkeme** [comment]
已修复
