### ISSUE TITLE
勋章亲密度赠送礼物顺序有问题

### ISSUE THREAD

**Issue by LenguesZ** [lkeme/BiliHelper-personal#35]
你好，发现
赠送礼物提升勋章亲密度的顺序，并非按照配置里制定的顺序赠送，而是按照在b站-直播-用户中心-佩戴中心，显示的顺序投喂。
在配置中，投喂列表上方的开关有打开。
刚刚，把名单里的除第一个以外的房间号删除，就可以向目标房间投喂了。
也发现，天选之人好像不工作了，不管设置0|0，1 都没有参加抽奖或进行关注参与抽奖。手动在手机上可以正常参与。

**Comment by lkeme** [comment]
投喂测试，5个勋章，配置里有两个勋章房间，我刚才复现测试是没问题的。

天选测试，0|0，1 都测试过，都能成功抽奖。

**Comment by shoucandanghehe** [comment]
我 打 脸 我 自 己
