### ISSUE TITLE
一直无法登录提示 服务繁忙, 请稍后再试

### ISSUE THREAD

**Issue by XZFFF** [lkeme/BiliHelper-personal#38]
Bilibili.ERROR: 登录失败 {"msg":"服务繁忙, 请稍后再试"} []

**Comment by lkeme** [comment]
![image](https://user-images.githubusercontent.com/19500576/85132488-79077c80-b26b-11ea-938c-69e76ec80adc.png)
  
我这边测试是没有问题的，请尝试换个环境或者IP重新试试。

**Comment by ganlvtech** [comment]
我也是，换了好几个 IP 终于找到一个能用的 IP 了，大概是 B 站的接口次数限制错了吧，好像没什么解决办法，不知道换一组 appkey 有没有用。

**Comment by lkeme** [comment]
登录组件在`dev`分支有更新，如果无法登录上可以尝试。
