### ISSUE TITLE
错误：活动已下线

### ISSUE THREAD

**Issue by ReddotCleaner** [lkeme/BiliHelper-personal#42]
错误：活动已下线，应该是B站又搞了什么新花样？

`[2020-08-26 15:33:52] BH.ERROR: check freeSilverCurrentTask failed! Error message: 活动已下线 [] []`

**Comment by 0x012FA733** [comment]
字面意思 银瓜子没有了 至于修不修随缘

**Comment by ReddotCleaner** [comment]
> 字面意思 银瓜子没有了 至于修不修随缘

好的，了解了，谢谢

**Comment by lkeme** [comment]
已更新，重新拉取。
