### ISSUE TITLE
建议设置小心心自动立即赠送

### ISSUE THREAD

**Issue by Snowflake-Pink** [lkeme/BiliHelper-personal#48]
B 站有一个机制，如果你的背包有当天得到的小心心比较多（大概16个），但是却没有送出去的话，是不会继续给小心心的。

现在一般我每天能挂到16个小心心，但是如果得一个送一个，一天最多可以得到24个

**Comment by lkeme** [comment]
暂时不会添加这个需求，适用范围比较小。  
小心心初衷只是为了点亮勋章，如果是为了牌子升级的话，也没太大必要。
毕竟现在是21级牌子起步，氪金升级。  
20级以内的牌子都排在十米开外了。

**Comment by x738722591** [comment]
> B 站有一个机制，如果你的背包有当天得到的小心心比较多（大概16个），但是却没有送出去的话，是不会继续给小心心的。
> 
> 现在一般我每天能挂到16个小心心，但是如果得一个送一个，一天最多可以得到24个

如图修改 BiliHelper-personal\src\plugin 目录下的 GiftSend.php
![1](https://user-images.githubusercontent.com/69028400/116870351-0023d000-ac45-11eb-8682-62a8735ca9bc.png)
![2](https://user-images.githubusercontent.com/69028400/116870355-03b75700-ac45-11eb-8638-efc50ad4bbda.png)

**Comment by lkeme** [comment]
这个什么所谓的机制对我似乎并没有效果。
![image](https://user-images.githubusercontent.com/19500576/116870998-2007c380-ac46-11eb-90e3-404bbc5493de.png)
