### ISSUE TITLE
push 代码 

### ISSUE THREAD

**Issue by lu79432** [lkeme/BiliHelper-personal#49]
开发了转发抽奖功能,可以merge么? 
还是这种功能不允许merge

**Comment by lu79432** [comment]
我添加了自动转发关注评论 #互动抽奖#  话题的方法

**Comment by lkeme** [comment]
才有空仔细看了下代码，可以merge，但是动态抽奖涉及的东西略多，会比较麻烦。  

如果是抽这种带抽奖系统的，那没太大必要做抽奖。  
![image](https://user-images.githubusercontent.com/19500576/101309647-d8902d80-3887-11eb-997b-b59cdac2be27.png)

```
# 这种类型的抽奖，过滤后几率很小。  
该抽奖已自动过滤异常行为，请以开奖结果为准
```

如果是抽带抽奖标签的 如`#互动抽奖# #转发抽奖#`的。  
这里就要涉及如何判定动态中奖、判定动态过期、转发关注评论等等。

**Comment by rhjdvsgsgks** [comment]
如果愿意的话可以加个“自动删除过期抽奖动态”的功能，不愿的话我以后可能会尝试写一下并pr上来（估计不怎么好看就是了）

**Comment by lu79432** [comment]
> 如果愿意的话可以加个“自动删除过期抽奖动态”的功能，不愿的话我以后可能会尝试写一下并pr上来（估计不怎么好看就是了）

[自动删除过期抽奖动态] 已经实现了

**Comment by lu79432** [comment]
> 才有空仔细看了下代码，可以merge，但是动态抽奖涉及的东西略多，会比较麻烦。
> 
> 如果是抽这种带抽奖系统的，那没太大必要做抽奖。
> ![image](https://user-images.githubusercontent.com/19500576/101309647-d8902d80-3887-11eb-997b-b59cdac2be27.png)
> 
> ```
> # 这种类型的抽奖，过滤后几率很小。  
> 该抽奖已自动过滤异常行为，请以开奖结果为准
> ```
> 
> 如果是抽带抽奖标签的 如`#互动抽奖# #转发抽奖#`的。
> 这里就要涉及如何判定动态中奖、判定动态过期、转发关注评论等等。

做的就是  #互动抽奖# #转发抽奖# 这种动态的自动 转发+ 关注 +评论 也做了过期删除. 
目前未实现的就是自动填写中奖信息以及 推送中奖通知. 因为没有中过奖 完全不知道中奖的数据结构是啥样的.......

**Comment by lkeme** [comment]
只有带有
![image](https://user-images.githubusercontent.com/19500576/101348157-288de500-38c6-11eb-93a5-b108dc6b4bf0.png)
这个符号的动态抽奖。  
才能通过`lottery_time`或者`https://api.vc.bilibili.com/lottery_svr/v1/lottery_svr/lottery_notice`查询是否中奖。    
`#互动抽奖# #转发抽奖#` 这类标签的动态，都查不了的。

**Comment by lu79432** [comment]
是的，所以我现在都不知道怎么验证。。。因为没有中过奖。。。



---原始邮件---
发件人: "lkeme"<notifications@github.com&gt;
发送时间: 2020年12月7日(周一) 晚上8:00
收件人: "lkeme/BiliHelper-personal"<BiliHelper-personal@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Possible"<794329728@qq.com&gt;;
主题: Re: [lkeme/BiliHelper-personal] push 代码  (#49)




 
只有带有
 
 这个符号的动态抽奖。
 才能通过lottery_time或者https://api.vc.bilibili.com/lottery_svr/v1/lottery_svr/lottery_notice查询是否中奖。
 #互动抽奖# #转发抽奖# 这类标签的动态，都查不了的。

**Comment by lu79432** [comment]
不知道是对方通过私信方式联系还是怎么弄



---原始邮件---
发件人: "lkeme"<notifications@github.com&gt;
发送时间: 2020年12月7日(周一) 晚上8:00
收件人: "lkeme/BiliHelper-personal"<BiliHelper-personal@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Possible"<794329728@qq.com&gt;;
主题: Re: [lkeme/BiliHelper-personal] push 代码  (#49)




 
只有带有
 
 这个符号的动态抽奖。
 才能通过lottery_time或者https://api.vc.bilibili.com/lottery_svr/v1/lottery_svr/lottery_notice查询是否中奖。
 #互动抽奖# #转发抽奖# 这类标签的动态，都查不了的。

**Comment by lu79432** [comment]
> 只有带有
> ![image](https://user-images.githubusercontent.com/19500576/101348157-288de500-38c6-11eb-93a5-b108dc6b4bf0.png)
> 这个符号的动态抽奖。
> 才能通过`lottery_time`或者`https://api.vc.bilibili.com/lottery_svr/v1/lottery_svr/lottery_notice`查询是否中奖。
> `#互动抽奖# #转发抽奖#` 这类标签的动态，都查不了的。

动态这种，我没有中过，所以不知道中奖之后是up通过私信联系，还是怎么弄。

**Comment by rhjdvsgsgks** [comment]
> [自动删除过期抽奖动态] 已经实现了

感谢，那我就不重复造轮子了

**Comment by lu79432** [comment]
> 只有带有
> ![image](https://user-images.githubusercontent.com/19500576/101348157-288de500-38c6-11eb-93a5-b108dc6b4bf0.png)
> 这个符号的动态抽奖。
> 才能通过`lottery_time`或者`https://api.vc.bilibili.com/lottery_svr/v1/lottery_svr/lottery_notice`查询是否中奖。
> `#互动抽奖# #转发抽奖#` 这类标签的动态，都查不了的。

我已经发起merge请求了,你看着A一下

**Comment by lkeme** [comment]
已合并哦，如果这部分代码有问题等等，后续麻烦跟进一下，谢谢~

**Comment by rhjdvsgsgks** [comment]
好像在 clearDynamic 里只要抽奖动态失效了则对抽奖的发布者都会取关，并没有计算是否在 group 中，这样如果一个转发了一个已关注的up的抽奖动态，当这个抽奖失效，也会取关这个up

**Comment by rhjdvsgsgks** [comment]
另外希望加个“只转发已关注up的抽奖”的功能，最好是从 getDynamicTab 里过滤出抽奖动态再转发，从 getAwardTopic 里过滤已关注的up感觉可能会漏（毕竟与个人动态列表相比大了许多，而且是在实时变化的）

**Comment by lu79432** [comment]
> 另外希望加个“只转发已关注up的抽奖”的功能，最好是从 getDynamicTab 里过滤出抽奖动态再转发，从 getAwardTopic 里过滤已关注的up感觉可能会漏（毕竟与个人动态tab列表相比大了许多，而且是在实时变化的）

**Comment by lu79432** [comment]
> 好像在 clearDynamic 里只要抽奖动态失效了则对抽奖的发布者都会取关，并没有计算是否在 group 中，这样如果一个转发了一个已关注的up的抽奖动态，当这个抽奖失效，也会取关这个up
> （不会php，不知道看的对不对

ok ,已经加了过滤了. 刚提了 merge

**Comment by rhjdvsgsgks** [comment]
> 另外希望加个“只转发已关注up的抽奖”的功能，最好是从 getDynamicTab 里过滤出抽奖动态再转发，从 getAwardTopic 里过滤已关注的up感觉可能会漏（毕竟与个人动态tab列表相比大了许多，而且是在实时变化的）

这个功能会加吗？
