### ISSUE TITLE
手机上的termux

### ISSUE THREAD

**Issue by Winter-is-comingXK** [lkeme/BiliHelper-personal#53]
$ php index.php
[2021-01-13 21:35:13] BH.INFO: 欢迎使用 BiliHelper Personal 当前版本 0.6.7.* [] []

Fatal error: Uncaught ValueError: Path cannot be empty in /data/data/com.termux/files/home/BiliHelper-personal/src/core/Curl.php:153
Stack trace:
#0 /data/data/com.termux/files/home/BiliHelper-personal/src/core/Curl.php(153): file_get_contents('', false, Resource id #67)
#1 /data/data/com.termux/files/home/BiliHelper-personal/src/core/Log.php(108): BiliHelper\Core\Curl::request('get', '')
#2 /data/data/com.termux/files/home/BiliHelper-personal/src/core/Log.php(74): BiliHelper\Core\Log::callback(200, 'INFO', '\xE6\xAC\xA2\xE8\xBF\x8E\xE4\xBD\xBF\xE7\x94\xA8 Bi...')
#3 /data/data/com.termux/files/home/BiliHelper-personal/src/core/Env.php(52): BiliHelper\Core\Log::info('\xE6\xAC\xA2\xE8\xBF\x8E\xE4\xBD\xBF\xE7\x94\xA8 Bi...')
#4 /data/data/com.termux/files/home/BiliHelper-personal/src/core/App.php(25): BiliHelper\Core\Env->inspect_configure()
#5 /data/data/com.termux/files/home/BiliHelper-personal/index.php(17): BiliHelper\Core\App->__construct()
#6 {main}
  thrown in /data/data/com.termux/files/home/BiliHelper-personal/src/core/Curl.php on line 153
$

**Comment by Winter-is-comingXK** [comment]
$ php -v
PHP 8.0.1 (cli) (built: Jan  7 2021 14:53:07) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.1, Copyright (c) Zend Technologies

**Comment by lkeme** [comment]
php8.*的问题，尚未兼容到，请使用php7.*
