### ISSUE TITLE
<s>[增强] 添加Github Actions 配置支持</s>

### ISSUE THREAD

**Issue by poly000** [lkeme/BiliHelper-personal#58]
Github Actions可以设置环境变量
可以写一个部署脚本修改配置文件
登录用帐密 或者用户直接更新Cookie
重要的是不需要在服务器等等运行

**Comment by Fcatme** [comment]
将白嫖进化的更彻底？

**Comment by poly000** [comment]
Github Actions有时间限制…… 但应该够嫖

**Comment by krl2333** [comment]
我之前干过，现在投不了币点不了赞了
![Screenshot_2021-02-10-13-23-33-01](https://user-images.githubusercontent.com/67739170/107468795-9fd04580-6ba3-11eb-8fe1-b26853ae35f9.jpg)

![Screenshot_2021-02-10-13-24-06-17](https://user-images.githubusercontent.com/67739170/107468809-a5c62680-6ba3-11eb-9291-29029211a480.jpg)

**Comment by poly000** [comment]
> 我之前干过，现在投不了币点不了赞了
> ![Screenshot_2021-02-10-13-23-33-01](https://user-images.githubusercontent.com/67739170/107468795-9fd04580-6ba3-11eb-8fe1-b26853ae35f9.jpg)
> 
> ![Screenshot_2021-02-10-13-24-06-17](https://user-images.githubusercontent.com/67739170/107468809-a5c62680-6ba3-11eb-9291-29029211a480.jpg)

可能是登录IP检测……

**Comment by poly000** [comment]
登录IP检测以及非持续运行…… 感觉不行
