### ISSUE TITLE
希望增加中奖之后通过邮件等方式提醒

### ISSUE THREAD

**Issue by XokoukioX** [lkeme/BiliHelper-personal#65]
希望中奖之后增加一个提醒功能。要不然每天去查终端会很麻烦。

**Comment by lkeme** [comment]
邮件通知暂不会考虑，脚本已经提供6种通知方式，详情参考：https://github.com/lkeme/BiliHelper-personal/wiki/%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E8%AF%A6%E8%A7%A3#%E9%80%9A%E7%9F%A5%E8%AE%BE%E7%BD%AE
