### ISSUE TITLE
[需要帮助] Waiting for recovery!

### ISSUE THREAD

**Issue by poly000** [lkeme/BiliHelper-personal#66]
```
BH.WARNING: (Curl) => CURl -> RETRY: 2 ERROR: cURL error 35: OpenSSL SSL_connect: Connection reset by peer in connection to passport.bilibili.com:443  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) ERRNO: 0 STATUS:  Waiting for recovery! [] []
```

**Comment by lkeme** [comment]
网络问题，更换网络或查看[wiki/常见问题#2-curl-error-60-ssl-certificate-problem](https://github.com/lkeme/BiliHelper-personal/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#2-curl-error-60-ssl-certificate-problem)尝试解决。

**Comment by poly000** [comment]
> 网络问题，更换网络或查看[wiki/常见问题#2-curl-error-60-ssl-certificate-problem](https://github.com/lkeme/BiliHelper-personal/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#2-curl-error-60-ssl-certificate-problem)尝试解决。

已经尝试不验证SSL证书…… 失败
正在尝试切换网络

**Comment by poly000** [comment]
solved
