### ISSUE TITLE
天选时刻的自动取关功能有问题

### ISSUE THREAD

**Issue by SekiBetu** [lkeme/BiliHelper-personal#75]
天选时刻的自动取关似乎只是把关注的人转移到了默认分组，并没有取关
![image](https://user-images.githubusercontent.com/38283893/114295307-14a5fa00-9ad7-11eb-8a69-041a0198fa74.png)

**Comment by SekiBetu** [comment]
可能不是天选时刻，我把天选关了，那个英雄联盟赛事也会自动关注回来，不清楚哪个功能
![image](https://user-images.githubusercontent.com/38283893/114304686-2606fa80-9b07-11eb-8cf7-7f414833760e.png)

**Comment by SekiBetu** [comment]
![image](https://user-images.githubusercontent.com/38283893/114304748-6cf4f000-9b07-11eb-996d-62f95361a3a1.png)
找到了，是这个活动，这是哪个功能的，直播统一活动?

**Comment by lkeme** [comment]
USE_CAPSULE，但是这个理论上应该不会自动关注的，都没写这个功能，不排除抽奖自动关注。

**Comment by SekiBetu** [comment]
> USE_CAPSULE，但是这个理论上应该不会自动关注的，都没写这个功能，不排除抽奖自动关注。

大佬你可以直接打开这个功能测试的，自动关注
![image](https://user-images.githubusercontent.com/38283893/114313724-38466000-9b2a-11eb-8ba7-888981cc5568.png)
刚才取关的，又给关上了

**Comment by lkeme** [comment]
![image](https://user-images.githubusercontent.com/19500576/114313861-e2be8300-9b2a-11eb-9711-bc737442c6d1.png)
这些是你自己关注的，还是自动关注的。

**Comment by SekiBetu** [comment]
自动的，我不玩lol的

**Comment by lkeme** [comment]
那你用了其他脚本的吧，我这个不会自动关注的。
![image](https://user-images.githubusercontent.com/19500576/114313932-3204b380-9b2b-11eb-87b0-cd1cec46a3bc.png)
这是我开了这个功能挂的号。

**Comment by SekiBetu** [comment]
![image](https://user-images.githubusercontent.com/38283893/114314004-7ee88a00-9b2b-11eb-99e9-61116f43c5a6.png)
我的配置，没有其他脚本

**Comment by SekiBetu** [comment]
按这个配置是绝对自动关注一堆号的

**Comment by SekiBetu** [comment]
我拿了个小号直接运行了一晚上
![image](https://user-images.githubusercontent.com/38283893/114314075-ce2eba80-9b2b-11eb-81f3-8574901f3753.png)
多了10个英雄联盟相关的，不会自动取关

**Comment by lkeme** [comment]
应该不是这个活动的，这个活动的有效期是不会执行的。
![image](https://user-images.githubusercontent.com/19500576/114314133-046c3a00-9b2c-11eb-92e6-b198fd7e1acb.png)

这样，你把敏感信息去掉，直接把这份配置文件发我，我找个号测试一下

**Comment by SekiBetu** [comment]
> 应该不是这个活动的，这个活动的有效期是不会执行的。
> [![image](https://user-images.githubusercontent.com/19500576/114314133-046c3a00-9b2c-11eb-92e6-b198fd7e1acb.png)](https://user-images.githubusercontent.com/19500576/114314133-046c3a00-9b2c-11eb-92e6-b198fd7e1acb.png)
> 
> 这样，你把敏感信息去掉，直接把这份配置文件发我，我找个号测试一下

发了，在上面，我是本地搭建了心跳服务器，其他就是账号密码没填

**Comment by lkeme** [comment]
大概运行多久出现的

**Comment by SekiBetu** [comment]
刚才英雄联盟好像是直播在打比赛，我取关之后自动关注回去的速度就几分钟，现在不清楚，我试试

**Comment by SekiBetu** [comment]
这个脚本有记录日志的吗，是只有nohup才行？

**Comment by lkeme** [comment]
是有日志记录的，在配置文件-程序设置部分，完整日志需要开调试模式。

**Comment by lkeme** [comment]
另外 ，我刚才自查了一下，应该不是我的脚本问题。

```log
# 节奏风暴|丢弃率(0-100)|尝试数(范围值)
USE_STORM=true
STORM_DROPRATE=0
STORM_ATTEMPT=2,4

# 破产机|每日竞猜次数|每次竞猜硬币(1-10)|下注(1.压大,2.压小,3.随机)
USE_COMPETITION=false
COMPET_MAX_NUM=20
COMPET_MAX_COIN=10
COMPET_STAKE=1

# 天选时刻|抽取类型(0: 无限制; 1: 关注主播; 2: 粉丝勋章; 3大航海； 4用户等级；5主站等级)|自动取关(测试功能)|过滤关键词|逗号分隔
USE_ANCHOR=true
ANCHOR_UNFOLLOW=false
ANCHOR_TYPE=0
ANCHOR_FILTER_WORDS=

# 活跃弹幕|弹幕房间(为空则随机)|弹幕内容(为空则随机)
USE_DANMU=true
DANMU_ROOMID=9522051
DANMU_CONTENT=

# 视频投币|random(随机热门)/fixed(关注列表)|投币稿件数(每日任务最大5)
USE_ADD_COIN=true
ADD_COIN_MODE=random
ADD_COIN_NUM=5

# 自动转发抽奖动态
AUTO_DYNAMIC = false
# 自动取关未中奖动态
CLEAR_DYNAMIC = false
# 强制清除抽奖组关注
CLEAR_GROUP_FOLLOW = false
# 更改自动回复语言
AUTO_REPLY_TEXT = 从未中奖，从未放弃[doge]
```

配置差异只有以上部分，理论上是没有自动关注的。

**Comment by lkeme** [comment]
先确认下是否有什么相关的浏览器插件、油猴脚本、或其他挂机软件脚本等。

**Comment by SekiBetu** [comment]
> 先确认下是否有什么相关的浏览器插件、油猴脚本、或其他挂机软件脚本等。

我小号是刚才第一次从电脑上登录，小号除了服务器就没在任何地方登陆过

**Comment by SekiBetu** [comment]
这两天没有出现了，玄学

**Comment by SekiBetu** [comment]
英雄联盟的一系列号好像和我从扯上关系了，这两个月，每几天就会自动关注，手动取关，算了算了，我直接把他们分成一组关注着了
