### ISSUE TITLE
[feature request] 将抽奖动态结果/删除加入到消息推送中

### ISSUE THREAD

**Issue by rhjdvsgsgks** [lkeme/BiliHelper-personal#76]
将抽奖动态结果/删除加入到消息推送中，在消息中附上抽奖的信息（源动态的链接、抽奖信息等）

**Comment by poly000** [comment]
抽奖结果要读“@我的”…… 此外要提取相关抽奖链接（如果 _@我的_ 消息中存在）

**Comment by rhjdvsgsgks** [comment]
> 抽奖结果要读“@我的”…… 此外要提取相关抽奖链接（如果 _@我的_ 消息中存在）
> 而且似乎很难判断是不是中奖的@
> 可以考虑推送所有“@我的”？

不就是把
https://github.com/lkeme/BiliHelper-personal/blob/061634cddfc4952aacb00e714881867690be2a00/src/plugin/Forward.php#L128..L157
里的 msg 后面插个 notice 发出来就行了吗，没必要这么麻烦吧

**Comment by poly000** [comment]
> > 抽奖结果要读“@我的”…… 此外要提取相关抽奖链接（如果 _@我的_ 消息中存在）
> > 而且似乎很难判断是不是中奖的@
> > 可以考虑推送所有“@我的”？
> 
> 不就是把
> https://github.com/lkeme/BiliHelper-personal/blob/061634cddfc4952aacb00e714881867690be2a00/src/plugin/Forward.php#L128-L157
> 
> 
> 里的 msg 后面插个 notice 发出来就行了吗，没必要这么麻烦吧

这个是官方渠道的吧…… 很多抽奖是非官方渠道 因为官方渠道有一定条件（创作力等等）

**Comment by rhjdvsgsgks** [comment]
> 这个是官方渠道的吧…… 很多抽奖是非官方渠道 因为官方渠道有一定条件（创作力等等）

那你也应该去新开个 issue 请求添加非官方抽奖，我这只是在现有功能上加了一行消息推送

**Comment by poly000** [comment]
> 
> 
> > 这个是官方渠道的吧…… 很多抽奖是非官方渠道 因为官方渠道有一定条件（创作力等等）
> 
> 那你也应该去新开个 issue 请求添加非官方抽奖，我这只是在现有功能上加了一行消息推送

不必…… 消息推送已经有了

**Comment by rhjdvsgsgks** [comment]
> > > 这个是官方渠道的吧…… 很多抽奖是非官方渠道 因为官方渠道有一定条件（创作力等等）
> > 
> > 
> > 那你也应该去新开个 issue 请求添加非官方抽奖，我这只是在现有功能上加了一行消息推送
> 
> 不必…… 消息推送已经有了

你确定有了吗？我说的“消息推送”指的是 `Notice::push` 这种，这在 Forward.php 中根本没出现过，哪来的“已经有了”？

**Comment by rhjdvsgsgks** [comment]
@poly000 还有你为什么老是删回复，如果没有引用别人还以为我在回复空气

**Comment by poly000** [comment]
> 
> 
> > > > 这个是官方渠道的吧…… 很多抽奖是非官方渠道 因为官方渠道有一定条件（创作力等等）
> > > 
> > > 
> > > 那你也应该去新开个 issue 请求添加非官方抽奖，我这只是在现有功能上加了一行消息推送
> > 
> > 
> > 不必…… 消息推送已经有了
> 
> 你确定有了吗？我说的“消息推送”指的是 `Notice::push` 这种，这在 Forward.php 中根本没出现过，哪来的“已经有了”？

抱歉 看wiki的Notice看错了……
删回复是因为引用已经有文字

**Comment by rhjdvsgsgks** [comment]
> 删回复是因为引用已经有文字

引用只是为了表现出我是在哪条进行回复，并不能取代一个人发了条回复所表现出来的“我发了条回复”的事实
