### ISSUE TITLE
报错？？？

### ISSUE THREAD

**Issue by mentlesoul** [lkeme/BiliHelper-personal#8]
大佬不知道啥问题会这样报错，刚运行index.php就会这样
PHP Warning:  Use of undefined constant AF_INET - assumed 'AF_INET' (this will throw an Error in a future version of PHP) in C:\Users\31445\Desktop\BiliHelper-master\BiliHelper-personal-master\vendor\clue\socket-raw\src\Factory.php on line 78
PHP Warning:  Use of undefined constant SOCK_STREAM - assumed 'SOCK_STREAM' (this will throw an Error in a future version of PHP) in C:\Users\31445\Desktop\BiliHelper-master\BiliHelper-personal-master\vendor\clue\socket-raw\src\Factory.php on line 78
PHP Warning:  Use of undefined constant SOL_TCP - assumed 'SOL_TCP' (this will throw an Error in a future version of PHP) in C:\Users\31445\Desktop\BiliHelper-master\BiliHelper-personal-master\vendor\clue\socket-raw\src\Factory.php on line 78
PHP Warning:  call_user_func() expects parameter 1 to be a valid callback, class 'BiliHelper\Plugin\StormRaffle' not found in C:\Users\31445\Desktop\BiliHelper-master\BiliHelper-personal-master\src\core\App.php on line 51
PHP Warning:  call_user_func() expects parameter 1 to be a valid callback, class 'BiliHelper\Plugin\GiftRaffle' not found in C:\Users\31445\Desktop\BiliHelper-master\BiliHelper-personal-master\src\core\App.php on line 51
PHP Warning:  call_user_func() expects parameter 1 to be a valid callback, class 'BiliHelper\Plugin\PkRaffle' not found in C:\Users\31445\Desktop\BiliHelper-master\BiliHelper-personal-master\src\core\App.php on line 51
PHP Warning:  call_user_func() expects parameter 1 to be a valid callback, class 'BiliHelper\Plugin\GuardRaffle' not found in C:\Users\31445\Desktop\BiliHelper-master\BiliHelper-personal-master\src\core\App.php on line 51
PHP Warning:  call_user_func() expects parameter 1 to be a valid callback, class 'BiliHelper\Plugin\AnchorRaffle' not found in C:\Users\31445\Desktop\BiliHelper-master\BiliHelper-personal-master\src\core\App.php on line 51
PHP Fatal error:  Uncaught Error: Call to undefined function Socket\Raw\socket_create() in C:\Users\31445\Desktop\BiliHelper-master\BiliHelper-personal-master\vendor\clue\socket-raw\src\Factory.php:177
Stack trace:
#0 C:\Users\31445\Desktop\BiliHelper-master\BiliHelper-personal-master\vendor\clue\socket-raw\src\Factory.php(78): Socket\Raw\Factory->create()
#1 C:\Users\31445\Desktop\BiliHelper-master\BiliHelper-personal-master\vendor\clue\socket-raw\src\Factory.php(253): Socket\Raw\Factory->createTcp4()
#2 C:\Users\31445\Desktop\BiliHelper-master\BiliHelper-personal-master\vendor\clue\socket-raw\src\Factory.php(23): Socket\Raw\Factory->createFromString()
#3 C:\Users\31445\Desktop\BiliHelper-master\BiliHelper-personal-master\src\plugin\AloneTcpClient.php(166): Socket\Raw\Factory->createClient()
#4 C:\Users\31445\Desktop\BiliHelper-master\BiliHelper-personal-master\src\plugin\AloneTcpClient.php(56): BiliHelper\Plugin\AloneTcpClient::openConnect()
#5 C:\Users\31445\Desktop\BiliHelper-master\BiliHelper-personal-master\src\plugin\Al in C:\Users\31445\Desktop\BiliHelper-master\BiliHelper-personal-master\vendor\clue\socket-raw\src\Factory.php on line 177

**Comment by lkeme** [comment]
麻烦有错误的时候自己先尝试搜索一下？ `php.ini 里开启 php_sockets.dll`

**Comment by mentlesoul** [comment]
> 麻烦有错误的时候自己先尝试搜索一下？ `php.ini 里开启 php_sockets.dll`

呃但是开启sockets后运行，到
C:\Users\31445\Desktop\BiliHelper-master\BiliHelper-personal-master>php index.php
[2020-02-20 13:40:17] Bilibili.INFO: 开始启动程序... [] []
[2020-02-20 13:40:17] Bilibili.INFO: 正在检查令牌合法性... [] []
[2020-02-20 13:40:17] Bilibili.INFO: 令牌有效期: 2020-03-20 22:16:18 [] []
[2020-02-20 13:40:22] Bilibili.NOTICE: 主站任务: av90259127观看成功! [] []
[2020-02-20 13:40:22] Bilibili.NOTICE: 主站任务: av90293141分享成功! [] []
[2020-02-20 13:40:23] Bilibili.NOTICE: 每日礼包领取成功 [] []
[2020-02-20 13:40:23] Bilibili.INFO: WEB端 发送心跳正常! [] []
[2020-02-20 13:40:23] Bilibili.INFO: APP端 发送心跳正常! [] []
[2020-02-20 13:40:23] Bilibili.INFO: 正在检查每日任务... [] []
[2020-02-20 13:40:23] Bilibili.INFO: 检查任务「双端观看直播」... [] []
[2020-02-20 13:40:23] Bilibili.NOTICE: 任务未完成，请等待 [] []
[2020-02-20 13:40:23] Bilibili.INFO: 检查任务「每日签到」... [] []
[2020-02-20 13:40:23] Bilibili.WARNING: 签到失败 {"msg":"今日已签到过,无法重复签到"} []
[2020-02-20 13:40:23] Bilibili.NOTICE: 今天所有的宝箱已经领完! [] []
[2020-02-20 13:40:24] Bilibili.INFO: 活跃弹幕发送成功! [] []
[2020-02-20 13:40:24] Bilibili.INFO: 正在获取勋章列表... [] []
[2020-02-20 13:40:24] Bilibili.INFO: 勋章列表获取成功! [] []
[2020-02-20 13:40:24] Bilibili.NOTICE: 你没有需要签到的应援团! [] []
C:\Users\31445\Desktop\BiliHelper-master\BiliHelper-personal-master>
这一步就会退出不知道是什么问题
