### ISSUE TITLE
windows10 下使用docker desktop 运行，求助

### ISSUE THREAD

**Issue by creboy** [lkeme/BiliHelper-personal#81]
配置好ini文件后，通过docker run -itd --rm -v user.ini:/app/conf/user.ini lkeme/bilihelper-personal 启动，出现如下提示：
![微信截图_20210524152010](https://user-images.githubusercontent.com/27350646/119311583-d5f18b00-bca3-11eb-865d-5fdfe96ec6ca.png)

这是运行成功了吗?有没有日志？

**Comment by poly000** [comment]
不要把Composer以root/超级用户运行！
