### ISSUE TITLE
关于天选抽奖

### ISSUE THREAD

**Issue by dd178** [lkeme/BiliHelper-personal#83]
挂了一天，看了眼日志，天选抽奖参加的只有13次。那个框起来的天选日志推送是22/16，参加和成功都是0/0，为什么我的抽奖频率这么低？关键词过滤没填，就算过滤掉那些没价值的天选挂一天应该也会有一两百次抽奖的啊，是要设置什么吗

**Comment by lkeme** [comment]
分区监控只监控了10个左右房间，所以这个数值比较正常。
