### ISSUE TITLE
无法参与天选

### ISSUE THREAD

**Issue by clones134** [lkeme/BiliHelper-personal#84]
这个是从昨天开始发现的（5.29），之前配置相同，运行环境相同
经测试，账号能正常参与抽奖
请问这个怎么解决
![image](https://user-images.githubusercontent.com/85053867/120097702-a7245a80-c164-11eb-8d4f-4bea3f9aae4c.png)

**Comment by lkeme** [comment]
独立监控在维护，所以稍微等等。

**Comment by clones134** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月30日(星期天) 下午4:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lkeme/BiliHelper-personal] 无法参与天选 (#84)





 
Closed #84.

**Comment by SekiBetu** [comment]
https://github.com/lkeme/bilibili-pcheartbeat
自己部署一个本地的，然后配置文件改成本地地址 127.0.0.1:3000
