### ISSUE TITLE
BH.WARNING: (XliveHeartBeat) => 直播间信息获取失败 [] []

### ISSUE THREAD

**Issue by Justwithme** [lkeme/BiliHelper-personal#87]
![image](https://user-images.githubusercontent.com/23739803/120878951-77f16b80-c5f2-11eb-8d7b-60b1efa1bc0f.png)
![image](https://user-images.githubusercontent.com/23739803/120878975-9c4d4800-c5f2-11eb-81d9-ef5d77e34b3c.png)
额，我这是进小黑屋了吗？

**Comment by lkeme** [comment]
412了，最好是1ip1号，或者多账号关闭一些频繁执行任务。
