### ISSUE TITLE
账号异常发不了验证码的解决办法

### ISSUE THREAD

**Issue by lovezm** [lkeme/BiliHelper-personal#89]
换了IP 且修改了密码
还是会有异常，而且手动处理这个连接的验证码也是不行  还有什么办法吗
https://www.bilibili.com/h5/project-msg-auth/verify?ct=geetest&recaptcha_token=a8175e4448d44d9d8bfdfe61cfeaa1f9&gee_gt=1c0ea7c7d47d8126dda19ee3431a5f38&gee_challenge=bc7f1a478fbcb85baeac3c36a67b1ac8&hash=c6b9f4b82dc3aff22c08159d5aae16b5

**Comment by poly000** [comment]
换手机号登陆试试？

**Comment by lkeme** [comment]
非BUG，极验点选或滑动验证，账号体质问题，异地，IP不对都会导致，可客户端多成功登录几次后同局域网重试，或者尝试手机号登录。
