### ISSUE TITLE
不能用手机号登录，貌似会整形溢出

### ISSUE THREAD

**Issue by aoteman5255661** [lkeme/BiliHelper-personal#97]
最后得到的手机号是2147483647

**Comment by aoteman5255661** [comment]
树莓派上是这样，php7.3 和php8都不行，  pc上又是好的

**Comment by lkeme** [comment]
请不要发这种无意义的Issue，无法从语义中提取有用的东西。  

> 请参考 #73 的提交bug方法

**Comment by aoteman5255661** [comment]
在32位系统中，无法用手机号登陆

**Comment by lkeme** [comment]
请不要发这种无意义的Issue，无法从语义中提取有用的东西。  

> 请参考 #73 的提交bug方法

...  
没有对应的设备来及时复现问题，也不可能因为一句话就挨着排查一遍登录流程。  
我需要的是日志，报错，截图等等，来定位具体一点的位置。  

```
1.尽量带上脱敏后的log。
2.尽量带上关键截图。
3.尽量带上错误提示。
4.以及当前的软件版本\PHP版本。
```

**Comment by wuan11** [comment]
> 在32位系统中，无法用手机号登陆

woc牛啊。我整了半天没找到原因原来是x86的问题
把php换成x64直接解决
